### ISSUE TITLE
Using self-defined clock_gettime to modify CLOCK_MONOTONIC time not work  in libevent-2.1.12-stable

### ISSUE THREAD

**Issue by moyotar** [libevent/libevent#1080]
os: debian 9.12

For testing my timer (use `evtimer_add`), I used a self-defined `clock_gettime` to jump `CLOCK_MONOTONIC` time ahead. My timer can be called normally in `libevent-2.1.5-beta` but not in `libevent-2.1.12-stable`.

Why? And how to fix?

**Comment by azat** [comment]
Take a look at [`EVENT_BASE_FLAG_PRECISE_TIMER`](https://libevent.org/doc/event_8h.html#acfef69af45abee54725f40f7f29986c5af6080f1d7c5067868cbc749d1cfe56e9)

Before 6cce7458d0f94e320f201eb5be94866e6918d66c due to an error CLOCK_MONOTONIC always used, but after that fix CLOCK_MONOTONIC_COARSE had been used by default.

**Comment by moyotar** [comment]
Thanks a lot!
