### ISSUE TITLE
could I do not lock evbuffer when only have one single read and single write

### ISSUE THREAD

**Issue by fubing2015** [libevent/libevent#1095]
Hi All, I have a question about evbuffer's lock. Now I use the bufferevent_socket_new to create the tcp socket.

If I only use one thread named A to call bufferevent_write, and of course the main thread of libevent named B will send these data. Do I need to add the BEV_OPT_THREADSAFE to the options of bufferevent_socket_new method?
Is it necessary to add the lock to evbuffer in the model with one single thread to read as well as one single thread to write since evbuffer is FIFO.

Bisides, we will only add the data to the bottom of evbuffer. And my libevent verison is 2.0.21.

Thanks

**Comment by azat** [comment]
>Is it necessary to add the lock to evbuffer in the model with one single thread to read as well as one single thread to write since evbuffer is FIFO.

If you access evbuffer from different threads you should use locks (since it updates some internal fields)

>If I only use one thread named A to call bufferevent_write, and of course the main thread of libevent named B will send these data. Do I need to add the BEV_OPT_THREADSAFE to the options of bufferevent_socket_new method?

Yes, since you are accessing evbuffer (plus there can be some trickery during connect).
But you can use socketpair to avoid locks (although I'm not sure that this is the better alternative, but you can test this), and use one bufferevent for reading from socketpair and another for writing, then you will not need locks (since socketpair will transfer the data).

>And my libevent verison is 2.0.21.

This is too old, I would strongly recommend to upgrade to the last stable (it should be mostly fully compatible with 2.0.21x, maybe except for deprecated for 15 years APIs)

**Comment by fubing2015** [comment]
Thanks. That help me a lot.
