### ISSUE TITLE
libevent tests are much slower on Linux, is this "easy" to improve?

### ISSUE THREAD

**Issue by emmenlau** [libevent/libevent#1103]
I'm happily building libevent on Linux, Windows and Mac since more than 4 years. The build is usually fine, but for some reason, the typical test times differ hugely between platforms. Typically, I get (on similar hardware):
 - Linux: 20 Minutes
 - Windows: 6 Minutes
 - MacOS: 2 Minutes

I can see that this is maybe just an artefact of testing and does not reflect the actual performance of libevent. However I was wondering if there is something that can be done about it, either on my side or libevents? The libevent tests on Linux take a reasonably large fraction of our whole CI build time, and it would be great to safe some time.

Do you know about anything that may make the tests particularly slow? Do you also see on your CI that Linux tests would be much slower than other platforms?

**Comment by azat** [comment]
>Typically, I get (on similar hardware):

For which command? I guess the problem is that the build matrix on linux is the most huge, you can try run in parallel

You can also take a look at our [CI](https://github.com/libevent/libevent/tree/master/.github/workflows), and build and test on linux takes
- ~3 mins under cmake
- ~4:30 under autotools (hm)
