### ISSUE TITLE
How to solve close_wait?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#1112]
When it will occur? Is my service not send close? How to solve it in system level?

**Comment by azat** [comment]
@okayabc your issues are too short, please provide as much details as possible:
- under what circumstances you see sockets in CLOSE_WAIT?
- why do you think that this is a problem for you?
- output of `ss` and a sample code will also help

From [rfc793](https://tools.ietf.org/html/rfc793):

>    CLOSE-WAIT - represents waiting for a connection termination request
    from the local user.

So this means that the kernel receive FIN, but you client does detect this, because you do not monitor events for these fd.
