### ISSUE TITLE
event_new for Windows event handles

### ISSUE THREAD

**Issue by davinci26** [libevent/libevent#1117]
Hey,

I am wondering if there is a way to have an `event` struct that operates over a Windows event `HANDLE`. You can create an event handle with [CreateEventA](https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-createeventa).

I want to use this to achieve similar behavior `EV_SIGNAL` on Windows. This is quite useful to catch `ctrl+c` events etc. 

Is this use case supported? I couldn't find anything on the documentation page.

**Comment by azat** [comment]
Hi!

No, `CreateEventA` is not supported by the libevent, but patches are always welcome!

**Comment by davinci26** [comment]
I can try to implement this. Any pointer on some existing code that would relevant and help me with the implementation?

Conceptually it should be doable but I am not well versed in libevent internals

**Comment by azat** [comment]
Actually I never heard about CreateEventA till now (and never bother about it too), so I can't share any relevant code how to work this this (except for maybe https://doc.qt.io/qt-5/qwineventnotifier.html, but qt event loop is different).

But in terms of libevent, how you can poll is HANDLE ready or not? If I read correctly then you can use IOCP? Libevent has minimal support of iocp, so I guess they can be used.

Also can you describe how they can be used for signals? AFAIR they are pretty basic events, (since there set SetEvent API, and this looks similar to event_active)

**Comment by zhengfish** [comment]
Did you ever run this sample libevent-2.1.12-stable\sample\event-read-fifo.c on Windows-10 successfully?
I got failed on this line:
`
event_base_dispatch(base);
`
after some debugging, I found that it failed with a error code: 100038.
`
    // Returns 0 if successful, -1 if an error occurred, or 1 if we exited because no events were pending or active.
    int rc = event_base_dispatch(base);
    if (rc != 0)
    {
        fprintf(stderr, "error: %d\n", GetLastError());
        event_base_free(base);
        return 1;
    }
`

**Comment by azat** [comment]
I'm not sure that `GetLastError()` is a good signal here, since this is an error of some syscalls that is done by event_base_dispatch.
What was the return code, -1?
I'm not a windows fan, is there any tool like strace on linux to see which syscall fails? Or maybe you can debug this in debugger or with printing at least?

**Comment by zhengfish** [comment]
Hello, Sir,
Yes, it return -1 on failed.
The error code 10038 means -- 10038 (WSAENOTSOCK): Socket operation on nonsocket.
I noticed that it did a mandatory data type cast from a HANDLE to evutil_socket_t:
`
#ifdef _WIN32
    evfifo = event_new(base, (evutil_socket_t)socket, EV_READ | EV_PERSIST, fifo_read, event_self_cbarg());
#else
`
Does this make sense?

I'd like to know whether the libevent can support the Windows HANDLE data structure before I do some debugging.

with regards.
