### ISSUE TITLE
Get peer certificate in evhttp_request_new() callback

### ISSUE THREAD

**Issue by mgorbachyov** [libevent/libevent#1121]
Hello.
With release-2.1.12-stable code in evhttp_request_new() callback can not get peer certificate:
```
--- a/sample/https-client.c
+++ b/sample/https-client.c
@@ -53,11 +53,12 @@ http_request_done(struct evhttp_request *req, void *ctx)
        char buffer[256];
        int nread;
+       struct bufferevent *bev = (struct bufferevent *) ctx;
+
        if (!req || !evhttp_request_get_response_code(req)) {
                /* If req is NULL, it means an error occurred, but
                 * sadly we are mostly left guessing what the error
                 * might have been.  We'll do our best... */
-               struct bufferevent *bev = (struct bufferevent *) ctx;
                unsigned long oslerr;
                int printed_err = 0;
                int errcode = EVUTIL_SOCKET_ERROR();
@@ -82,6 +83,15 @@ http_request_done(struct evhttp_request *req, void *ctx)
            evhttp_request_get_response_code(req),
            evhttp_request_get_response_code_line(req));
+       SSL* ssl = bufferevent_openssl_get_ssl(bev);
+       if (ssl) {
+               X509* cert = SSL_get_peer_certificate(ssl);
+               if (!cert) {
+                       fprintf(stderr, "no cert\n");
+                       exit(1);
+               }
+       }
+
$ make https-client
...
[100%] Built target https-client
$ bin/https-client -url https://www.kernel.org/
https server 'www.kernel.org' has this certificate, which looks good to me:
/CN=kernel.org
Response line: 200 OK
no cert
```
It happens due to commit 29b7a516fdd5a71994f37482562f2fd9691959ee
It breaks some code that worked with libevent 2.1.8.
How can one get peer certificate in evhttp_request_new() callback with latest libevent?

**Comment by ploxiln** [comment]
You should do this in `cert_verify_callback()`. You'll also need to change the user-data `ctx` that is passed to `cert_verify_callback()` and `evhttp_request_new()` in order to get this data where you want it. In the sample, the `host` string is passed as the user-data `ctx` for `cert_verify_callback()`. You'll want to instead use a custom struct that has a pointer to the `host` string, and other fields for the data you extract from the `X509` peer certificate, which `cert_verify_callback()` fills in. `evhttp_request_new()` currently takes the `bev` for the callback user data `ctx`, and you'll also replace that with the same custom struct (which can also contain a pointer to the `bev` for the existing purpose of looking up the ssl error, though I'm guessing that also no longer works now, due to the ssl reset). So the callback `http_request_done()` will get the custom struct with the fields you filled in `cert_verify_callback()` and it will be able to free this context struct.

**Comment by mgorbachyov** [comment]
@ploxiln Thank you very much for the explanation!
