### ISSUE TITLE
event_base_new_with_config -> error

### ISSUE THREAD

**Issue by X-Crack** [libevent/libevent#1236]
[warn] event_base_new_with_config: Unable to make base notifiable.

**Problems caused by insufficient system resources. (Probably the port)**

It is suspected to be a bug, because the memory allocation has failed

libevent Version: release-2.1.12-stable
msvc Version:  vs 2022

OS: windows 10 21H2 LTSC

![bug](https://user-images.githubusercontent.com/45416520/145055678-28a91632-c6ed-46be-a0a5-070cea25c5b3.png)

![vs ver](https://user-images.githubusercontent.com/45416520/145055691-52a56a09-fb0f-40ca-a5bc-074b047dc6eb.png)

**Comment by azat** [comment]
So, what you are suggesting? Or you mean that it is a permanent error in your environment?

**Comment by X-Crack** [comment]
> So, what you are suggesting? Or you mean that it is a permanent error in your environment?

emmm.....

No good advice, very sorry.

I just mentioned that in my system, if the system is low on resources. There will be a memory allocation failure.

Instead of just returning a nullptr pointer, an assertion should be given here to tell the developer that the system is running low on resources

**Comment by ploxiln** [comment]
libevent is low-level enough software, that it is generally desired for it to not abort, but rather report errors for the caller to handle. This way low-level system software that wants to be resilient can be so. For example, if a service manager was using libevent and got this error, it may just say "cannot start new service: insufficient memory", and keep other services running, instead of just killing the whole system.

**Comment by azat** [comment]
Indeed, generic libraries should not abort the application.
