### ISSUE TITLE
sha256 are not stable for 2.1.8-stable and 2.1.12-stable zip 

### ISSUE THREAD

**Issue by teresanovielloatinstana** [libevent/libevent#1249]
This morning the sha256 of the following files changed at least one time each:

https://github.com/libevent/libevent/archive/release-2.1.8-stable.zip
https://github.com/libevent/libevent/archive/release-2.1.12-stable.zip

We use the above links and the sha256 for a bazel workspace, so we rely on their stability.

Is there a reason why this is happening? Should be change our approach?

**Comment by ploxiln** [comment]
The content of those files are generated automatically by GitHub based on the git tag referenced, and those two git tags have not changed, so that's pretty weird. It may be that the download was intercepted/blocked/failed occasionally for your systems (thus affecting the hash of the result).

It is recommended to use an archive generated by the release process:
https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz

That includes a generated configure script and some other bits, whereas the archive generated automatically by github from a git tag does not. But in any case, the archives should not be changing, and do not appear to me to have changed.

**Comment by azat** [comment]
>The content of those files are generated automatically by GitHub based on the git tag referenced, and those two git tags have not changed, so that's pretty weird. It may be that the download was intercepted/blocked/failed occasionally for your systems (thus affecting the hash of the result).

@ploxiln good guess!
@teresanovielloatinstana are you sure that those files are complete? What are the sizes?

>It is recommended to use an archive generated by the release process:

Right. And we have GPG signature for those archives.

>That includes a generated configure script and some other bits, whereas the archive generated automatically by github from a git tag does not. But in any case, the archives should not be changing, and do not appear to me to have changed.

Indeed, so you don't need to run `./autogen.sh` if you are using official tar balls (not the one that github automatically can generate).
