### ISSUE TITLE
Add ULT support to libevent

### ISSUE THREAD

**Issue by janciesko** [libevent/libevent#1358]
Currently [this test app](https://github.com/sandialabs/MPI-Partix/blob/main/apps/ultcorrectness1.cpp) hangs with executions with multiple streams and when OMPI is configured to use a ULT lib. To support this case, we would need ULT-aware threading primitives in libevent, similarly to ULT support in OMPI. One reference implementation is this one: 

https://github.com/shintaro-iwasaki/libevent/commits/2.0.22-abt

I think we should consider a runtime selectable ULT library implementation in libevent even though it might bring one additional function call indirection and roofline size of lock types. Externalizing ULT lib support in OMPI and libevent and targeting a generic`libult` seems to be a more maintainable path forward.

**Comment by azat** [comment]
Hi!

I haven't looked deeply to this, but it seems that it will be enough to provide separate threading primitives, or you want not a static primitives (like pthread/win32 that libevent has now), but dynamic?

This is also not a problem, since acquiring mutex has bigger overhead that indirect function call anyway.

**Comment by azat** [comment]
>I can add the static threading primitives for Argobots and Qthreads if you like?

Great!
But I think better to add dynamic primitives, since this code is too specific.
