### ISSUE TITLE
libevent failed to build from source on Debian Bookworm with glibc 2.36

### ISSUE THREAD

**Issue by babelouest** [libevent/libevent#1393]
Hello,

I'm digging up an old question about `evutil_secure_rng_add_bytes`. I'm maintaining the package libevent in Debian, and lately I had a failed to build from source (FTBFS) for libevent whith glibc 2.36: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1023284

It seems that the transition process would be too late for bookworm, so another proposed solution is to add a patch that will make `evutil_secure_rng_add_bytes` a no-op function. It was mentioned in an old issue that such a solution is not a good thing to do: https://github.com/libevent/libevent/issues/615#issuecomment-421182890

Considering that glibc implements `arc4random` functions, but not `arc4random_addrandom`, is the solution to no-op `evutil_secure_rng_add_bytes` acceptable?

Debian manifests: https://salsa.debian.org/debian/libevent/

**Comment by babelouest** [comment]
@azat , friendly ping with this question, please?

**Comment by azat** [comment]
@babelouest hello and sorry for the delay!

I don't like the idea of making `evutil_secure_rng_add_bytes` no-op, since this may has security concerns - the caller may assume that it indeed seeds bytes to the RNG while it does not.

And I also don't want distros to have custom patches to build libevent, but the problem is that you have expectations for the list of symbols in the library, you don't want to remove `evutil_secure_rng_add_bytes` from it because this will introduce ABI incompatibility?

**Comment by babelouest** [comment]
> this may has security concerns - the caller may assume that it indeed seeds bytes to the RNG while it does not.

I understand your concern, although I'm wondering, and please feel free to contradict me if I'm wrong:

if `evutil_secure_rng_add_bytes` is no-oped, does it mean not enough entropy when the app calls `evutil_secure_rng_get_bytes` in this case?
If the function `ev_arc4random_buf` doesn't need more entropy to generate a secure enough random number, then would no-oping `evutil_secure_rng_add_bytes` have no consequence in the a application?

> And I also don't want distros to have custom patches to build libevent, but the problem is that you have expectations for the list of symbols in the library, you don't want to remove evutil_secure_rng_add_bytes from it because this will introduce ABI incompatibility?

Yes, the ABI incompatibility, the fact that the bug in Debian is tagged as `serious` and we are too close to release Bookworm makes it a little bit tricky to solve.

I totally understand your concern about Debian patching libevent though. This patch would be present in Debian bookworm, but the next package releases will be vanilla.

**Comment by azat** [comment]
About `evutil_secure_rng_add_bytes`/`evutil_secure_rng_get_bytes` and `*arc4*`.

When there is no arc4 provided in the system, libevent ships it's own.
In this case, it also provide some helpers (i.e. `evutil_secure_rng_add_bytes`, `evutil_secure_rng_set_urandom_device_file`) to add **more** entropy, entropy is initialize anyway (see `arc4_stir`), but making `evutil_secure_rng_add_bytes` no-op, does not looks good for security.

From the other point of view, `evutil_secure_rng_add_bytes` make sense only when libevent ships arc4 functions, since only in this case it seeds RNG with additional data. So I guess it is OK to make `evutil_secure_rng_add_bytes` no-op if arc4 is provided in the system.

But, to make it more explicit, let's convert the signature of the function from `void evutil_secure_rng_add_bytes` to `int evutil_secure_rng_add_bytes` and return `-1` if it is as no-op (and update the documentation block).

@babelouest can you submit a patch?

**Comment by floppym** [comment]
I'm working on a patch for this, but I am concerned that changing the signature of `evutil_secure_rng_add_bytes` will introduce another ABI break. Do you really want that?

**Comment by floppym** [comment]
A cleaner solution might be to use the bundled arc4random implementation if libc does not provide both `arc4random` and `arc4random_addrandom`.

**Comment by AdrianBunk** [comment]
> I don't like the idea of making `evutil_secure_rng_add_bytes` no-op, since this may has security concerns - the caller may assume that it indeed seeds bytes to the RNG while it does not.

> But, to make it more explicit, let's convert the signature of the function from `void evutil_secure_rng_add_bytes` to `int evutil_secure_rng_add_bytes` and return `-1` if it is as no-op (and update the documentation block).

@azat You could just update the documentation to make it clear that the caller of `evutil_secure_rng_add_bytes` may not assume that it seeds bytes to the RNG without changing the function signature.

Current callers would anyway not notice that their existing code is now ignoring a new return value, so documenting that people should not have an assumption that is wrong when the function is a no-op will be sufficient.

**Comment by kroeckx** [comment]
> From the other point of view, `evutil_secure_rng_add_bytes` make sense only when libevent ships arc4 functions, since only in this case it seeds RNG with additional data. So I guess it is OK to make `evutil_secure_rng_add_bytes` no-op if arc4 is provided in the system.

I assume you mean that if the system provides arc4random, you assume it's a version that knows how to get random information, and doesn't need to application to provide it.

> I am concerned that changing the signature of evutil_secure_rng_add_bytes will introduce another ABI break

The return value is not is not actually part of the ABI, so it's not an ABI break, but it is part of the API, and things might break when the version you build against does not match it, if they also start to check the return value. I suggest we just don't return something. If you do want to change the return value, I suggest you change the soname.

I've created #1427

**Comment by azat** [comment]
>Current callers would anyway not notice that their existing code is now ignoring a new return value, so documenting that people should not have an assumption that is wrong when the function is a no-op will be sufficient.

@AdrianBunk We can add `warn_unused_result` attribute

**Comment by azat** [comment]
>I'm working on a patch for this, but I am concerned that changing the signature of evutil_secure_rng_add_bytes will introduce another ABI break. Do you really want that?

I'm OK with this, since it is had been long time since the last libevent release and 2.2 should be done eventually, and it is OK to change the function signature there.

Also ABI should not be broken by changing return value in C

**Comment by azat** [comment]
>The return value is not is not actually part of the ABI, so it's not an ABI break, but it is part of the API, and things might break when the version you build against does not match it, if they also start to check the return value. I suggest we just don't return something. If you do want to change the return value, I suggest you change the soname.

@kroeckx ok, make sense.

**Comment by babelouest** [comment]
Thanks, the Debian package has been updated too!
