### ISSUE TITLE
Using event_enable_debug_logging() at runtime

### ISSUE THREAD

**Issue by stickies-v** [libevent/libevent#1426]
The changelogs for 2.1 [state](https://github.com/libevent/libevent/blob/2e52bace9f9998826bd3819af328efc8d18decf9/whatsnew-2.1.txt) that:

> You can now turn on debug logs at runtime using a new function,
  event_enable_debug_logging().

[Based on this](https://github.com/bitcoin/bitcoin/pull/10150#discussion_r110255587), bitcoin/bitcoin#10150 introduced RPC functionality to toggle libevent debug logging at runtime, after creation of the event base.

The libevent documentation [states](https://libevent.org/libevent-book/Ref1_libsetup.html) that "You must make any changes to these settings before you call any other part of the Libevent library. If you don’t, Libevent could wind up in an inconsistent state.", and the [headers](https://github.com/libevent/libevent/blob/bcefdbc67a4b18c5dce4420dfa3e83b3dfa16f6f/include/event2/event.h#L791-L806) similarly state that "This is a global setting; if you are going to call it, you must call this before any calls that create an event-base. You must call it before any multithreaded use of Libevent."

As far as my (limited) understanding goes, the changelog and documentation seem to be at odds (unless runtime refers to the rather narrow time window before creation of an event base). Could anyone please clarify whether calling`event_enable_debug_logging()` at runtime (after event base creation) is indeed unsafe? As far as I know, we've not observed any actual issues with this implementation (introduced in 2017).

Largely mirrors the internal issue raised in https://github.com/bitcoin/bitcoin/issues/27182.

Thank you!

**Comment by azat** [comment]
Hi!

I don't see any possible issues with calling `event_enable_debug_logging` after creating of `event_base`, and basically anytime (except for maybe a TSan warning, since the code is not uses proper atomics, but this should not be a problem, but it can leads to loosing few messages before/after calling `event_enable_debug_logging` if you have concurrent libevent loop)

That said that you are safe to use it in anytime.

As for documentation vs changelog, changelog is a better place to look, since by documentation here you referring to a book that was written by @nmathewson and it is updated only occasionally (sigh).

@stickies-v maybe you can submit a patch to the https://github.com/libevent/libevent-book to address this?
