### ISSUE TITLE
Use checksec to scan the libevent_pthreads-2.1.so.7.0.1 file FORTIFY item is 'No'

### ISSUE THREAD

**Issue by xxz199539** [libevent/libevent#1551]
Hi, I buid my libevent use:
`tar -xzvf source/libevent-2.1.12-stable.tar.gz >>$init_path/install.log 2>&1
cd libevent-2.1.12-stable
./configure CFLAGS="-fstack-protector-all -s -O2 -fPIC -Wl,-z,relro,-z,now,-z,noexecstack -D_FORTIFY_SOURCE=2" \
                CPPFLAGS="-fstack-protector-all -s -O2 -fPIC -Wl,-z,relro,-z,now,-z,noexecstack -D_FORTIFY_SOURCE=2" \
                LDFLAGS="-pie -z relro -z now" && make && make install`

when i used checksec to scan files under libevent. Except for libevent_pthreads-2.1.so.7.0.1 and libevent_openssl-2.1.so.7.0.1, the FORTIFY items of other files are 'yes'. 

how to solve this problem？thanks.
![image](https://github.com/libevent/libevent/assets/38350849/c5f437d0-efb1-4847-978d-144967378023)

**Comment by azat** [comment]
I don't know what is checksec, but I have one idea - pthreads/ssl has extra libraries, and they had not been compiled with `-D_FORTICY_SOURCE`.

**Comment by azat** [comment]
Anyway it is not libevent's problem.

**Comment by xxz199539** [comment]
@azat Checksec is a bash script to check the properties of executables (like PIE, RELRO, Canaries, ASLR, Fortify Source).the website is https://github.com/slimm609/checksec.sh.
in fact,libevent_pthreads-2.1.so.7.0.1 has same extra libraries with others,like:
![image](https://github.com/libevent/libevent/assets/38350849/3a4e9972-1552-4af5-b6fa-bc619259e386)

**Comment by azat** [comment]
Ok, I've took at look at this checksec and this is how it works, it gets all the symbols with `_chk` from the libc and checks libraries against usage of such symbols if does not found - fails.

And the reason it prints NO for pthreads/openssl because there is no usage of any of this functions, because it is a simple wrapper against pthread.

That said that everything is OK in libevent, the problem is in this script, here a fix - https://github.com/slimm609/checksec.sh/pull/232

**Comment by xxz199539** [comment]
thanks
