### ISSUE TITLE
evhttp_connection_cb_cleanup "event_assign called on an already added event" 

### ISSUE THREAD

**Issue by gj12** [libevent/libevent#258]
I get the error: 
```
[err] event_assign called on an already added event 0x72ba50 (events: 0x0, fd: -1, flags: 0x81)
```
in this scenario:
1. event_base_loop(base,EVLOOP_NO_EXIT_ON_EMPTY);  running in another pthread.
2. evhttp connection retries set to >=2
3. add 100 requests to a not established evhttp_connection 
4. the target http server must be offline/not reachable

Reproducible with the following modifications to sample/https-client.c 
(start https-client with  -url http://127.0.0.1 -retries 2)

```diff
--- old.c       2015-06-19 15:50:58.635678158 +0200
+++ https-client.c      2015-06-19 15:48:23.085672893 +0200
@@ -38,6 +38,7 @@
 #include <event2/listener.h>
 #include <event2/util.h>
 #include <event2/http.h>
+#include <event2/thread.h>

 #include <openssl/ssl.h>
 #include <openssl/err.h>
@@ -45,9 +46,18 @@

 #include "openssl_hostname_validation.h"

+#include <pthread.h>
+#include <unistd.h>
+
 static struct event_base *base;
 static int ignore_cert = 0;

+static void*
+evbase_thread(void* p)
+{
+       event_base_loop(base,EVLOOP_NO_EXIT_ON_EMPTY);
+}
+
 static void
 http_request_done(struct evhttp_request *req, void *ctx)
 {
@@ -204,7 +214,11 @@
        struct evhttp_request *req;
        struct evkeyvalq *output_headers;
        struct evbuffer * output_buffer;
-
+       pthread_t thr;
+
+       event_enable_debug_mode();
+       evthread_use_pthreads();
+
        int i;

        for (i = 1; i < argc; i++) {
@@ -347,6 +361,8 @@
                return 1;
        }

+       pthread_create(&thr, NULL, evbase_thread, NULL);
+
        // Create OpenSSL bufferevent and stack evhttp on top of it
        ssl = SSL_new(ssl_ctx);
        if (ssl == NULL) {
@@ -359,7 +375,7 @@
        #endif

        if (strcasecmp(scheme, "http") == 0) {
-               bev = bufferevent_socket_new(base, -1, BEV_OPT_CLOSE_ON_FREE);
+               bev = bufferevent_socket_new(base, -1, BEV_OPT_CLOSE_ON_FREE|BEV_OPT_THREADSAFE);
        } else {
                bev = bufferevent_openssl_socket_new(base, -1, ssl,
                        BUFFEREVENT_SSL_CONNECTING,
@@ -384,8 +400,11 @@

        if (retries > 0) {
                evhttp_connection_set_retries(evcon, retries);
+
        }
-
+
+       for(i = 0; i < 100;++i)
+       {
        // Fire off the request
        req = evhttp_request_new(http_request_done, bev);
        if (req == NULL) {
@@ -425,7 +444,11 @@
                fprintf(stderr, "evhttp_make_request() failed\n");
                return 1;
        }
-
+       }
+
+       for(;;)
+               sleep(1);
+
        event_base_dispatch(base);

        evhttp_connection_free(evcon);
```

**Comment by deepakys** [comment]
This issue is also seen in libevent-2.1.5-beta with following patch to https-client.c sample file.
One additional periodic timer event with https-client is causing an assertion in library.

Issue occurs when https-client times out connecting to a unreachable destination. 

Libevent abort's as below when we run - ./https-client -url https://1.1.1.1

.....
.....
[debug] event_add: event 0x177be10, timeout in 144940 seconds 999143 useconds, call 0x7f135a353cb0
[debug] event_process_active: event_callback 0x177bf20, closure 3, call 0x7f135a56cca0
[debug] evhttp_error_cb: connection timeout for "1.1.1.1:443" on 6
[err] event_assign called on an already added event 0x177bd90 (events: 0x52, fd: 6, flags: 0x82)
Aborted

Patch:

diff --git a/sample/https-client.c b/sample/https-client.c
index fbd5de8..b59d3cb 100644
--- a/sample/https-client.c
+++ b/sample/https-client.c
@@ -38,6 +38,7 @@
 #include <event2/listener.h>
 #include <event2/util.h>
 #include <event2/http.h>
+#include <event2/event_struct.h>
 
 #include <openssl/ssl.h>
 #include <openssl/err.h>
@@ -47,6 +48,7 @@
 
 static struct event_base *base;
 static int ignore_cert = 0;
+struct timeval lasttime;
 
 static void
 http_request_done(struct evhttp_request *req, void *ctx)
@@ -185,6 +187,22 @@ static int cert_verify_callback(X509_STORE_CTX *x509_ctx, void *arg)
 	}
 }
 
+static void
+timeout_cb(evutil_socket_t fd, short event, void *arg)
+{
+	struct timeval newtime, difference;
+	double elapsed;
+
+	evutil_gettimeofday(&newtime, NULL);
+	evutil_timersub(&newtime, &lasttime, &difference);
+	elapsed = difference.tv_sec +
+	    (difference.tv_usec / 1.0e6);
+
+	printf("timeout_cb called at %d: %.3f seconds elapsed.\n",
+	    (int)newtime.tv_sec, elapsed);
+	lasttime = newtime;
+}
+
 int
 main(int argc, char **argv)
 {
@@ -204,9 +222,14 @@ main(int argc, char **argv)
 	struct evhttp_request *req;
 	struct evkeyvalq *output_headers;
 	struct evbuffer * output_buffer;
+	struct event timeout;
+	struct timeval tv;
 
 	int i;
 
+	event_enable_debug_mode();
+	event_enable_debug_logging(EVENT_DBG_ALL);
+
 	for (i = 1; i < argc; i++) {
 		if (!strcmp("-url", argv[i])) {
 			if (i < argc - 1) {
@@ -382,6 +405,7 @@ main(int argc, char **argv)
 		return 1;
 	}
 
+	evhttp_connection_set_timeout(evcon, 5);
 	if (retries > 0) {
 		evhttp_connection_set_retries(evcon, retries);
 	}
@@ -426,6 +450,15 @@ main(int argc, char **argv)
 		return 1;
 	}
 
+	/* Initalize one event */
+	event_assign(&timeout, base, -1, EV_PERSIST, timeout_cb, (void*) &timeout);
+
+	evutil_timerclear(&tv);
+	tv.tv_sec = 2;
+	event_add(&timeout, &tv);
+
+	evutil_gettimeofday(&lasttime, NULL);
+
 	event_base_dispatch(base);
 
 	evhttp_connection_free(evcon);

**Comment by ellzey** [comment]
> One additional periodic timer event with https-client is causing an assertion in library.

That is not the trigger. 

Short story: with this code (https-client.c), event_add/event_del is getting called over and over again; the culprit seems to be: `evhttp_connection_cb_cleanup` -> `evhttp_connection_reset_` -> `bufferevent_setfd` -> `bev->be_ops->ctrl(bev, BEV_CTRL_SET_FD, &d /*** fd == -1 ***/);` -> `be_openssl_ctrl` -> `set_handshake_callbacks(.., -1)` via

```C
        case BEV_CTRL_SET_FD:
                if (bev_ssl->underlying)
                        return -1;
                {
                        BIO *bio;
                        bio = BIO_new_socket(data->fd, 0);
                        SSL_set_bio(bev_ssl->ssl, bio, bio);
                        bev_ssl->fd_is_set = 1;
                }
                if (data->fd == -1)
                        bev_ssl->fd_is_set = 0;
                if (bev_ssl->state == BUFFEREVENT_SSL_OPEN)
                        return set_open_callbacks(bev_ssl, data->fd);
                else {
                        return set_handshake_callbacks(bev_ssl, data->fd);
                }
```

which if you look here:

```C
               int r1=0, r2=0;
                if (fd < 0 && bev_ssl->fd_is_set)
                        fd = event_get_fd(&bev->ev_read);
                if (bev_ssl->fd_is_set) {
                        event_del(&bev->ev_read);
                        event_del(&bev->ev_write);
                }
                event_assign(&bev->ev_read, bev->ev_base, fd,
                    EV_READ|EV_PERSIST|EV_FINALIZE,
                    be_openssl_handshakeeventcb, bev_ssl);
                event_assign(&bev->ev_write, bev->ev_base, fd,
                    EV_WRITE|EV_PERSIST|EV_FINALIZE,
                    be_openssl_handshakeeventcb, bev_ssl);
```

`event_del()` is never called, because `fd == -1`, `be_ssl->fd_is_set == 0` which is set from `BEV_CTRL_SET_FD` (and event_assign happened during `bufferevent_openssl_new_impl`).

To be honest, `bev_ssl->fd_is_set` is new to me; and it seems quite useless at a glance. 

I'm heading out of the office, will be back for more.

**Comment by gj12** [comment]
It's caused by this commit: https://github.com/libevent/libevent/pull/175/files

**Comment by deepakys** [comment]
Rolling back #175 did not work for me.
Following up on Mark's observation, using the patch below help's but has some errors on cleanup.

[debug] evhttp_error_cb: connection timeout for "1.1.1.1:443" on 6
[debug] event_del: 0x79cfe0 (fd 6), callback 0x7fb7e805fd70
[warn] Epoll MOD(4) on fd 6 failed.  Old events were 6; read change was 2 (del); write change was 0 (none); close change was 0 (none): Bad file descriptor
[debug] event_del: 0x79d060 (fd 6), callback 0x7fb7e805fd70
[debug] Epoll DEL(4) on fd 6 gave Bad file descriptor: DEL was unnecessary.
Response line: 0 (null)
[debug] timeout_next: event: 0x7fff6d81fe50, in 1 seconds, 0 useconds


<pre><code>
diff --git a/bufferevent_openssl.c b/bufferevent_openssl.c
index b30f90f..00e2dbe 100644
--- a/bufferevent_openssl.c
+++ b/bufferevent_openssl.c
@@ -1080,6 +1080,12 @@ set_handshake_callbacks(struct bufferevent_openssl *bev_ssl, evutil_socket_t fd)
                        event_del(&bev->ev_read);
                        event_del(&bev->ev_write);
                }
+               if (event_initialized(&bev->ev_read)) {
+                       event_del(&bev->ev_read);
+               }
+               if (event_initialized(&bev->ev_write)) {
+                       event_del(&bev->ev_write);
+               }
                event_assign(&bev->ev_read, bev->ev_base, fd,
                    EV_READ|EV_PERSIST|EV_FINALIZE,
                    be_openssl_handshakeeventcb, bev_ssl);
</code></pre>

**Comment by gj12** [comment]
I think this are 2 different problems. I get the crash with http and https.  Reverting #175 solves this for me, but introduces different problems later.

**Comment by ellzey** [comment]
@gj12 2 different problems maybe, but I think the cause is the same. This is a hard one.

**Comment by gj12** [comment]
I fixed the problem with this small change:

```diff
diff --git a/http.c b/http.c
index b577518..6ab705a 100644
--- a/http.c
+++ b/http.c
@@ -1272,6 +1272,11 @@ evhttp_connection_reset_(struct evhttp_connection *evcon)
                evcon->fd = -1;
        }

+       if (event_initialized(&evcon->retry_ev)) {
+                       event_del(&evcon->retry_ev);
+                       event_debug_unassign(&evcon->retry_ev);
+               }
+
        /* we need to clean up any buffered data */
        tmp = bufferevent_get_output(evcon->bufev);
        evbuffer_drain(tmp, evbuffer_get_length(tmp));
```

I had no time to test, if this fixes the cause of the problem or if this is just a workaround.

**Comment by ellzey** [comment]
It __feels__ like a workaround. But it __looks__ legit.

**Comment by gj12** [comment]
Normaly we don't have this problem, because the evhttp_error_cb calls evhttp_connection_free .evhttp_connection_free does the event_del(&evcon->retry_ev);. 
https://github.com/libevent/libevent/pull/175 moves evhttp_connection_reset_ before the evtimer_assign block. This causes the "double add". Calling evhttp_connection_free here would clean all pending requests. I just put the event_del(&evcon->retry_ev) stuff from evhttp_connection_free in  evhttp_connection_reset_ to clean the retry_ev. Another way is to clean the retry_ev in `evhttp_error_cb: case EVCON_CONNECTING:`

**Comment by azat** [comment]
I agree with that `!event_initialized()` stuff, however I'm trying to reproduce this without threads.
As for openssl it is a separate bug since it complains about `ev_read` it is not the same as `retry_ev`, and I'm trying to get rid off `fd_is_set` which looks pretty hackish to me too.

And also I found one race using program from the description, patch is here azat/libevent@2d16db2ad8c5e93d06de2406344f59e5f0af2e59

**Comment by azat** [comment]
I have a patches to fix this issue, @gj12 could test them?
- azat/libevent@2d16db2ad8c5e93d06de2406344f59e5f0af2e59 (just to avoid race in evdns)
- azat/libevent@fd6f4949450b3eddd8df250e5f3b64bcdd1a1c01 (fix for openssl)

**Comment by azat** [comment]
This issue have a lot of comments, to summarize all of them, in short:
- ```https-client with -url http://127.0.1.1 -retries 2``` (using azat/libevent@2de22d02c1b806f01300f3ce8d2a5081bf6f7f08) -- don't reproduce the issue after azat/libevent@2d16db2ad8c5e93d06de2406344f59e5f0af2e59
- ```https-client with -url http://127.0.1.1 -retries 2``` (using azat/libevent@22c632cc7675341bf548d37536a33f51de47105c) -- don't have any issues after azat/libevent@2d16db2ad8c5e93d06de2406344f59e5f0af2e59
- ```https-client with -url https://127.0.1.1 -retries 2``` (using azat/libevent@22c632cc7675341bf548d37536a33f51de47105c) -- don't have any issues after azat/libevent@2d16db2ad8c5e93d06de2406344f59e5f0af2e59 *and* azat/libevent@fd6f4949450b3eddd8df250e5f3b64bcdd1a1c01

That ```retry_ev``` timer double assigned because of wrong events del/add in ```bufferevent_openssl``` code.

IOW that two patches must fix this issue. Am I missed something?

**Comment by azat** [comment]
And here is the regression for this issue -- azat/libevent@cdafdf017eec36c3943b53383fe7c558fee020f5

**Comment by azat** [comment]
I'm closing this, if you can reproduce this issue with the latest libevent or/and after trying this https://github.com/libevent/libevent/issues/258#issuecomment-136860135 please reopen it.
