### ISSUE TITLE
[RFC] Associate arbitrary data with an event_base

### ISSUE THREAD

**Issue by theuni** [libevent/libevent#281]
In OO code, I often find myself wrapping a class around an event_base for use as some sort of connection manager. However, callback parameters are complicated in this scenario by the fact that the it's necessary to combine the real argument with a class reference in order to be able to call member functions. In cases where trivial data needs to be passed to callback functions, this is wasteful and gets complicated quickly, since new data structures need to be created on the heap just to pass an extra pointer.

I think it would be very helpful if an event_base could be given a pointer to some arbitrary data just like the callbacks, allowing for callbacks associated with that base to retrieve it without wasting the callback param.

I propose something along the lines of:

``` c
extern bool bufferevent_set_base_data(event_base* base, void* data);
extern void* bufferevent_get_base_data(event_base* base);
```

The following silly example shows how these might be used. In this case the base data is stored to a global, but obviously it would need to be stored in the event_base itself. Here, the class itself is stored as a pointer in the event_base, allowing member functions to be called much more easily.

``` c++
#include <event2/bufferevent.h>
#include <event2/event.h>

#include <assert.h>
#include <string.h>
#include <stdlib.h>

extern void* bufferevent_get_base_data(event_base* base);
extern bool bufferevent_set_base_data(event_base* base, void* data);

namespace {
  void* bufferevent_basedata;
} // namespace

void* bufferevent_get_base_data(event_base* base)
{
  if(!base) {
    return NULL;
  }

  // Return base-specific data here.
  return bufferevent_basedata;
}

bool bufferevent_set_base_data(event_base* base, void* data)
{
  if(!base) {
    return false;
  }

  // Set data in base here
  bufferevent_basedata = data;
  return true;
}

class ConnectionManager
{
public:
  ConnectionManager()
  : m_base(event_base_new()), m_sock(0)
  {
    bufferevent_set_base_data(m_base, this);
  }

  ~ConnectionManager()
  {
    event_base_free(m_base);
  }

  static void outgoing_conn(bufferevent *bev, short type, void *ctx)
  {
    assert(ctx);
    const char* initstr = static_cast<const char*>(ctx);
    if(type & BEV_EVENT_CONNECTED) {
      event_base* base = bufferevent_get_base(bev);
      ConnectionManager* mgr = static_cast<ConnectionManager*>(bufferevent_get_base_data(base));
      assert(mgr);
      evutil_socket_t sock = bufferevent_getfd(bev);
      mgr->InitConnection(bev, sock, initstr);
    }
    else {
        printf("connection failed\n");
    }
    bufferevent_free(bev);
  }

  bool Connect(const char* host, int port, const char* initstr)
  {
    printf("connecting to: %s:%i. sending: %s\n", host, port, initstr);
    bufferevent *bev = bufferevent_socket_new(m_base, -1, BEV_OPT_CLOSE_ON_FREE);
    if(bufferevent_socket_connect_hostname(bev, NULL, AF_UNSPEC, host, port) != 0) {
        return false;
    }
    bufferevent_setcb(bev, NULL, NULL, outgoing_conn, static_cast<void*>(const_cast<char*>(initstr)));
    return true;
  }

  bool Run(const char* host, int port, const char* initstr)
  {
    if (!Connect(host, port, initstr)) {
        return false;
    }
    return event_base_dispatch(m_base) != -1;
  }

  void InitConnection(bufferevent *bev, evutil_socket_t sock, const char* initstr)
  {
    m_sock = sock;
    printf("sock stored in ConnectionManager!\n");
    bufferevent_write(bev, initstr, strlen(initstr));
  }

private:
  event_base* m_base;
  evutil_socket_t m_sock;
};

int main(int argc, char *argv[])
{
  if(argc != 4) {
    printf("usage: %s [host] [port] [init string]\n", argv[0]);
    return 1;
  }
  if (ConnectionManager().Run(argv[1], atoi(argv[2]), argv[3])) {
    printf("success\n");
    return 0;
  }
  return 1;
}
```

**Comment by ellzey** [comment]
>  In cases where trivial data needs to be passed to callback functions, this is wasteful and gets complicated quickly, since new data structures need to be created on the heap just to pass an extra pointer.

While I am indifferent to such a feature, if the above is the case, and as you stated before  you would have to wrap a structure around the event_base (which is what most people do), you may have to rethink thing a little. 

In libevhtp, I allow for user-defined data to be set in just about every structure that exists, but it's pretty crappy to deal with.

But this feature isn't as simple as one may  think. Is the data in the base volatile, if so we have thread issues, and  more so, in that case, what is the point? One callback sets the data it wants, the other reads what it __thinks__ it wants, but another function has intercepted and written something else. (I only assume this because thee code above is not a const)

Deferred calls would be a mess.
Events with priorities would be a mess,
You have to set a callback to free the data safely each time you call 

If you're simply attempting to drop the overhead of allocating memory, why not just use a ring buffer sliced up with the size of the data you would normally allocate (including proper alignment)? There are many lockless implementations of this very specific algorithm.

This seems like a first-world c++ issue :)

Either way, this functionality would probably not go into 2.x; as it sounds like there _may_ be some edge cases that could catch us by surprise. 

```C++
namespace {
  void* bufferevent_basedata;
} // namespace

void* bufferevent_get_base_data(event_base* base)
{
  if(!base) {
    return NULL;
  }

  // Return base-specific data here.
  return bufferevent_basedata;
}
```

This is just fancy way of setting a global variable, in such a case, why not just do the obvious:  use a global variable. Heck, you can make it thread safe with gcc using __thread_t. (sure, some will whine about it, but it solves the problem for now, right?)

**Comment by theuni** [comment]
Heh, the globals used there are only placeholders. The comments were meant to indicate that in the real versions of these functions, they would be per-base pointers. Sorry for not making that more clear.

I can't argue against most of your points, they're all very reasonable. I suppose my only counter-argument is that I had a very simple use-case in mind, though you're right to assume that others would want more/different things.

I had assumed that the data would be immutable once set, and would not be subject to any cleanups. In a c++ class case, the data would be the class itself (the one holding the event_base), which would presumably be torn down automatically. The only reason to have the data is so that the callbacks can find the class they belong to, so I'm not really sure how threading issues would come into play.

**Comment by azat** [comment]
I'm agree with @ellzey, the point that your use case is just install-once-const and use, must works for every case not for you only (and indeed it can lead to errors in multi threaded environment).

**Comment by ellzey** [comment]
You can also research intrusive data structures; those help with those "wasted" bits.
