### ISSUE TITLE
2.1 stable release?

### ISSUE THREAD

**Issue by proppy** [libevent/libevent#285]
I'm curious if there is a timeline yet for a 2.1 stable release?

Does this list of issues capture accurately the work that's remaining:
https://github.com/libevent/libevent/labels/libevent-2.1

Thanks in advance for redirecting me to another discussion channel, if filing an issue is not the right way to start that conversation :)

**Comment by miniupnp** [comment]
won't the stable release be 2.2 ?

**Comment by azat** [comment]
@proppy creating an issue is okay, but I'm not sure that this is the correct way, since it will hanging here until 2.1 will be released, but let's leave this as-is for now.
As for remaining work, yep that list is pretty much full (more or less), and we are trying to fix them ASAP.

@miniupnp Next stable release will be 2.1, since there wasn't any 2.1 stable yet (but this is not so important 2.1 or 2.2 I guess).

**Comment by azat** [comment]
I've just created a [milestone](https://github.com/libevent/libevent/milestones/2.1) for **2.1**

**Comment by azat** [comment]
Cc: @libevent/maintainers

**Comment by hhakimi53** [comment]
Thanks first of all the work that's put in for the libevent.

Is there a timeline for stable release candidate for 2.1? 2.1.7 seems to much better for SSL functionality as compared to 2.0.22. Thanks

**Comment by azat** [comment]
@hhakimi53 yep, something like
https://github.com/libevent/libevent/milestone/1

**Comment by hhakimi53** [comment]
@azat thanks for the response. so are these all the blockers that needs to be resolved before a stable release?

**Comment by azat** [comment]
Yep, a few blockers, and a bunch of testing

**Comment by azat** [comment]
[Here it is!](http://archives.seul.org/libevent/users/Jan-2017/msg00003.html)
