### ISSUE TITLE
libevent-2.1.8-stable.tar.gz compile fail Under Windows 【urgent】

### ISSUE THREAD

**Issue by allenhfchen** [libevent/libevent#458]
![libevent build fail](https://cloud.githubusercontent.com/assets/12984542/22774651/068ff8c0-eee3-11e6-9918-63cadcce4b27.png)

when I compile the latest version of libevent(libevent-2.1.8-stable.tar.gz) under windows by vs2012 there are some errors.who can help me?

**Comment by azat** [comment]
So that the problem is in:
```c
struct http_server hs = { .port = 0, .ssl = ssl, };
```

And the problem is because vs2012 doesn't support c99, which has [Designated Initializers](https://gcc.gnu.org/onlinedocs/gcc/Designated-Inits.html)

I will fix it later, or you can send a patch/pull-request (it should be pretty trivial).

In the mean time, do you have newer VS? Since Visual Studio 14 2015 works [fine](https://ci.appveyor.com/project/nmathewson/libevent/build/job/ests1lkgvc4jm4m5)
