### ISSUE TITLE
expose evhttp_get_request

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#496]
I have a file descriptor. Maybe I got it from cmsg https://linux.die.net/man/3/cmsg maybe I made it with  socketpair http://man7.org/linux/man-pages/man2/socketpair.2.html. I'd like to treat it like an HTTP client, and have my `structure evhttp` process it.

To do that, I was hoping to call `evhttp_get_request`, however that function is static. Can we make it not static?

**Comment by azat** [comment]
So you want to make http requests over custom fd, and AFAIR the problem with http and custom fd is that it caches fd in http layer so firstly we need to drop this bit out of there, and then we can implement this.
I thought about this problem a while back, and partial solution will be #479, but this doesn't solve the reconnect part, (`evhttp_connection_set_retries`) that patch is absolutely fine, since it has already connected socket, but this will make things tricky for user (`evhttp_connection_set_retries` will be no-op for pre-connected sockets).
What I came with, is that we need something like connection hook, but not sure that adding it into http layer is a great idea, I though about adding it into bufferevent filter or adding some other bufferevent for this (and verify that stacking bufferevents with it will be fine).

As for suggested patch, evhttp_get_request is about server not client, or maybe I didn't get you. Do you have example of libevent usage after this patch?

**Comment by ghazel** [comment]
My use case is server, yes. So the retries don't apply either.

**Comment by ghazel** [comment]
I guess "treat it like an HTTP client" was ambiguous, sorry. I meant:

```c
while (1) {
    fd = my_magic_accept()
    evhttp_get_request(fd)
}
```

My application is a server, and the fd I have should be treated like an incoming connection.

**Comment by azat** [comment]
Looks hackish to me. Another hack that can be done without hacking around library is use `pipe2` to forward requests, what do you thinkg? In this case hack will be in your application only, not in the library.

**Comment by ghazel** [comment]
If I use`pipe2`, what do I do with the other fd?

**Comment by ghazel** [comment]
(the obvious answer to me would be to pass that fd to `evhttp_get_request()`)

**Comment by wjz2047** [comment]
MARK

**Comment by ghazel** [comment]
This change https://github.com/libevent/libevent/commit/1bdc91350ee30d3aa51fe809fd719c2c3183b445 made the situation even more complicated. Now `evhttp_get_request()` takes a `bev`, which would suite the needs of this issue, but it still takes an `fd` as well, and uses it to strangely replace the `fd` on the passed in `bev` https://github.com/libevent/libevent/blob/1bdc91350ee30d3aa51fe809fd719c2c3183b445/http.c#L4598 (why couldn't this have been done prior?)

**Comment by ghazel** [comment]
The work on this is captured in #1471
