### ISSUE TITLE
[2.1.8-stable] nmake fails on Visual Studio 2008

### ISSUE THREAD

**Issue by prixone** [libevent/libevent#497]
Hi,

I am not sure if you guys can re-issue a new [`.tar.gz` for the 2.1.8 stable on your site](https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz), but I've found 2 issues:

1. The file `test/print-winsock-errors.c` is missing from the test folder thus generating the test for it, will fail
2. The file `test/regress_http.c` have constructors that use `.` in front of the property which fails on VS2008 as error, for example `struct http_server hs = { .port = 0, .ssl = ssl, };` simple removing the property part of it `struct http_server hs = { 0, ssl, };` works but perhaps you may want to address it differently.

Fixing those 2 issues, compiling libevent-2.1.8-stable on Visual Studio 2008 using nmake is done without issues.

Lastly but not least, Thanks for this project!

**Comment by azat** [comment]
Hi @prixone 

We cannot re-issue existing tarball (once the tarball is published it must be immutable, so that people who already use it can depend on it), this issues will be fixed in the next minor update.
As for this two bits - patches are always welcome (if you are interested in this, if no, it is not a problem of course - I will fix this by myself).

And many thanks for the feedback!

**Comment by prixone** [comment]
@azat thanks for the response, I have 0 knowledge in c and I do not know if that minor fix I mentioned above would break it for any other OSes compilations nor would be able to text on other OSes, if that is not a problem, I did be glad to fill in a PR.

**Comment by azat** [comment]
Okay, then let me do this.

Just pushed two fixes for this, but please note, that *existing tarballs are immutable*, so this will be fixed only in the next releases.
