### ISSUE TITLE
accepting 500 connections or more from libevent  [update :: changed the config files but still not able to remove the error]

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#500]
Is there  any bug or issue being faced when 500 connections or more opened in a very small amount of time?
Error shown is 
[warn] Error from accept() call: Too many open files
from event_log in log.c

**Comment by ploxiln** [comment]
No. This can be caused by the open file handle limit (see `ulimit -n`) or the `listen()` backlog overflowing. Both of these can be raised.

**Comment by kushal4** [comment]
so what is the remedy behind it ,how do i solve it

**Comment by kushal4** [comment]
I have changed the open file limit value but still when i do ulimit -n it is showing 1024 instead of showing the updated value.I am using fedora 25 as my working platform

**Comment by azat** [comment]
You can:
- set this values in `/etc/security/limits.conf` and restart you box to apply changes
- use `prlimit` to adjust values for already runned process (and verify with `cat /proc/pid/limits` or again with `prlimit`)
- use `ulimit` and then start process *from the same* session (import thing about this is that by default you can raise NOFILE limit only to 4096, because default hard limit is 4096, if you need more you need to be root in short)
(some bits only for linux)

P.S. and there is a lot of documentation about this in google.

**Comment by kushal4** [comment]
hi, 
This may slightly  sort of out of context question but i have set the values in /etc/security/limits.conf as universally to all the users that would access this config file. Then when i am acccessing it via a regular user through ssh which is mostly said in google .Is this the best approach or is there any better way for setting it for any user

**Comment by azat** [comment]
You are not accessing this file manually to apply this limits, this will be done at login (in case of ssh it will be done by pam module I guess).

This limits can be applied only for user (see comments/examples) and on per-group basis too.

**Comment by kushal4** [comment]
yes i had to include that pam_limits.so too which was not included before
