### ISSUE TITLE
Request that CMakeLists.txt file be included in future official packages

### ISSUE THREAD

**Issue by dagostinelli** [libevent/libevent#502]
libevent has CMakeLists.txt in source control, but not in the [official release packages](https://github.com/libevent/libevent/releases).

My project uses CMake.  It has to pull from master instead of using test/verified release packages.

I hereby request that future packages include the relevant CMake infrastructure.

**Comment by azat** [comment]
Personally I don't have anything against including CMakeLists.txt into
release archive. Do you want to send a patch? Or should I do it by
myself?

Please note that autotools is more mature for now, but in future cmake
should be prefered over autotools (I don't think that I should write
here about the reasons for this). The reason why autotools should be
used is that cmake do not have all bits that autotools has (but a month
ago I fixed some general cmake issues, like absent of pkg-config files,
libevent_pthreads.so/libevent_openssl.so/...).

But all this is import for distros, because if libevent package will
miss libevent_pthreads.so then a lot of package builds can fail, which
is not the desire behaviour (and nobody want to dig into such issues),
but if you just need to package libevent for your own needs then you can
give cmake a try (I guess), and give us feedback (and that will be
great)!

You can track progress of cmake support here:
  https://github.com/libevent/libevent/milestone/2

P.S. for now it is empty, but I'm pretty sure that we will find
something else.

**Comment by azat** [comment]
And this is interesting one, right now to make dist archive we use `make dist` (so autotools), but if we have cmake then we don't need any autotools.

**Comment by kushal4** [comment]
the autotools part works nearly in all version and i think this is the safest way to compile :)

**Comment by azat** [comment]
@dagostinelli do you want it in the next minor libevent release (i.e. 2.1.9) ?
