### ISSUE TITLE
multi evconn_listener in the same program for splitting the connection ranges

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#504]
Hi,
Is there any scope in libevent where multiple evconn_listeners can be created in order to split connection ranges to be listened in multple ports for those connection ranges ?
Thanks,
Kushal

**Comment by azat** [comment]
Not sure what do you mean by "connection ranges" (if this is kind of port 1-1024 then not sure that it worth implementing), but you can just create X listeners:
```c
struct evconnlistener *endpoint = evconnlistener_new_bind(base, ...);
evconnlistener_enable(endpoint);
```

**Comment by kushal4** [comment]
suppose  i am stating  that  1st 500  connections  will  be listened on  port9876   via  1st evconnlistener
then  another  500  connections   listenend  on  port9877  via  2nd  evconnlistener.

**Comment by azat** [comment]
Maybe you just need to balance connections handling between listeners/threads? Since for me handling 500 connections on one port and next 500 on another is pretty useless.

**Comment by azat** [comment]
Also this doesn't look like an issue in libevent, so not sure that this is the best place for such questions. Can I ask you to use [mailing list](http://archives.seul.org/libevent/users/) for this?

**Comment by kushal4** [comment]
sorry i posted it here.Its not really an issue but i am just asking whether this facility is there or not :)

**Comment by azat** [comment]
And as for your issue, how could you do this if you client always connected to one port 9876, how it will know about it should connect to another port? Only if you will implement protocol for this it will be possible otherwise not (like `Location: ` in HTTP, but anyway you will cannot to 9876 port firstly, of course you can use something like `consul` to get active *master*, but it shouldn't be used in a such way here).

But you can split load into multiple threads for this you can create N bases (each has it own thread) and one listener, then you will send fd from listener (that accept it) to one of base:
  http://archives.seul.org/libevent/users/Mar-2016/msg00046.html

Also you can just fork after you had one listener, but this can be tricky (because you cannot control threads priorities/order).

**Comment by kushal4** [comment]
ok :) actually i was thinkin about an idea like, since I am trying to build an mqqt broker through this, i want to make clustured broker  through this implementation
