### ISSUE TITLE
Option for switching off native getaddrinfo

### ISSUE THREAD

**Issue by janekolszak** [libevent/libevent#505]
Hi there!
Great library!

I have a leaky getaddrinfo implementation. 
**How can I configure libevent to use it's impementation of getaddrinfo?** 
Configure script detects that getaddrinfo is there, but I still need to switch it off.

Thank you :)

**Comment by azat** [comment]
Hi @janekolszak 

Right now there is no such ability, can you describe what the oddity is?
The best option will be to detect this (i.e. during configuring, and patches are welcome), since if you can do this automatically it is not good to provide such switch, because it will only confuse others.

But with `cmake` you can switch it off by default (because cached variables used for functions detection), with:
```
cmake -DEVENT__HAVE_GETADDRINFO=NO
```

And thanks for the feedback!

**Comment by janekolszak** [comment]
Thanks,
I'm using v2.0.22 so I had to patch it. Good to know it's fixed in the cmake version.

There is a bug in getaddrinfo implementation in some eglibc versions:
https://bugs.launchpad.net/ubuntu/+source/eglibc/+bug/1364584

**Comment by ploxiln** [comment]
I think this is possible without patching, if you do

```
./configure libevent_cv_getaddrinfo=no
```

**Comment by janekolszak** [comment]
Tried this, didn't work.
