### ISSUE TITLE
read callback isnt fired for every socket on which the packet is recieved

### ISSUE THREAD

**Issue by kushal4** [libevent/libevent#508]
Hi,
I have opend around 750 unique socket  in my client program or in other words i have 750 connections communicating with the server(to be specific this is an mqtt broker i am talking about).I am using libevent code on the broker side itself.So,sometimes i notice that whenever a client sends a packet to the broker on a socket(this occurs on some socket only),the read callback is not called corresponding to the packet recieved on the broker for that socket.In this case.
How do i debug whether what has actually happened about why the read callback was not invoked at that time?
Thanks,
Kushal

**Comment by kushal4** [comment]
Furthur Debugging shows that within few fraction of milliseconds more than  50 packets arrives to different sockets , I am having some doubt regarding here,is polling affected due to this and each socket not getting notified of the read callback due to this?

**Comment by kushal4** [comment]
I suspect, when suppose i am giving 650 connection from one machine and random data packets are sent from these clients from the machine.When the packet transmission of these clients are nearly on the peak,I  have startes another 100 connection from another machine, after some time i see this issue occuring

**Comment by azat** [comment]
> How do i debug whether what has actually happened about why the read callback was not invoked at that time?

Maybe `strace` can help you, another reason for this can edge-triggered events, but I guess that you don't uses it, otherwise you will know this.

> more than 50 packets arrives to different sockets

Sounds like a bug in your code to me

> When the packet transmission of these clients are nearly on the peak,I have startes another 100 connection from another machine, after some time i see this issue occuring

maybe some issues with fd reusing

**Comment by kushal4** [comment]
<b>maybe some issues with fd reusing</b>
But,When  accept()   function  is  called  from the  server side (within  the  libevent   itself),the fd  which  is  generated   must  be  unique  unless  and  until    i  am  closing  any  connection,so  as  per  this  chances  of  reusing  of  fd  is  not there  as  per  my view

**Comment by ploxiln** [comment]
What you're trying to do does not sound very unusual, it sounds like the basic functionality of libevent that many developers and applications depend on. It would be best for you to assume that any problems you run into are due to (understandable) mistakes made by your code, not "bugs" in libevent (even though it may be tricky to use). This kind of low-level C and event-loop programming requires a lot of care, and systematic debugging.

If you can provide a complete compilable example that can reproduce a bug on a specified OS and archtecture, with absolutely minimal and clean code, that would be very helpful. It is truly a lot of hard work. Unfortunately, without a specific proposed fix (pull request), or a minimal clean demonstration program, we can only give vague tips. Check your limits, be careful with your file descriptors, etc.
