### ISSUE TITLE
[HELP] evhttp_send_reply_chunk do not send chunk until calling evhttp_send_reply_end?

### ISSUE THREAD

**Issue by Tyrant2010** [libevent/libevent#536]
I want to implement a mini http server for online video viewing while downloading video data from video server. I store the video file in multiple cache files. So I use evhttp_send_reply_chunk to send data, but i found that no reply packet was sent until evhttp_send_reply_end is called. Could I make evhttp send data while I call evhttp_send_reply_chunk?

I do the following steps:
1: browser send a request to my mini http server
2: my mini server create mutiple threads to downloading the video from another video server
3: while thread 0 finish downloading, send data by evhttp_send_reply_chunk, thread 1 finish downloading, send data by evhttp_send_reply_chunk........
4. call evhttp_send_reply_end

**Comment by mason-hale** [comment]
I'd like to add to this issue - I've experienced the exact same frustration. I've been trying to send large amounts of data over a single HTTP request, but the amount is too large for one evhttp_send_reply. So, I turned to chunking, which seems like it should have been the perfect solution--it ostensibly sends the content in pieces so that a single buffer won't become overfilled (which causes the crashing on my machine). And yet, it doesn't work at all.

I stepped through the code using GDB (both my implementation and libevent's own http/stream_out test) and found that evhttp_send_reply_chunk merely pushes the overflowing buffer back a step. The content is progressively added to req->evcon->bufev->output (where req is the evhttp_request) with each chunk call. This buffer grows until, as OP mentioned, evhttp_send_reply_end flushes its content into the network. Nothing is sent over the network until all the chunks have been loaded into this intermediary buffer, a confounding discovery that seems to eliminate all utility of this encoding method. I furthermore did a practical test in which I inserted sleep calls in between the chunk calls and, indeed, the server simply hanged until all the sleep and chunk calls had gone through. If chunking were working properly, pieces of the request should have been sent incrementally. 

Are we missing something? It just doesn't seem like chunking is working at all like it's supposed to. Any help would be greatly appreciated.

**Comment by ploxiln** [comment]
`evhttp_send_reply_chunk()` does work. Here's a minimal working example:

```c
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>

#include <event2/event.h>
#include <event2/buffer.h>
#include <event2/http.h>

struct event_base *evbase_ctx;
struct evhttp *evhttp_ctx;

struct trickle_ctx {
	struct evhttp_request *req;
	struct event *tm_ev;
	int remaining;
};

void trickle_cb(int fd, short events, void *ctx)
{
	struct trickle_ctx *tinfo = ctx;

	struct evbuffer *buf = evbuffer_new();
	evbuffer_add_printf(buf, "just a bit of data ...\n");
	evhttp_send_reply_chunk(tinfo->req, buf);
	evbuffer_free(buf);

	tinfo->remaining--;
	if (tinfo->remaining <= 0) {
		evhttp_send_reply_end(tinfo->req);
		return;
	}
	struct timeval timeout = { 1, 0 };
	event_add(tinfo->tm_ev, &timeout);
}

void request_cb(struct evhttp_request *req, void *ctx)
{
	evhttp_send_reply_start(req, 200, "OK");

	struct trickle_ctx *tinfo = malloc(sizeof(struct trickle_ctx));
	tinfo->req = req;
	tinfo->tm_ev = event_new(evbase_ctx, -1, 0, trickle_cb, tinfo);
	tinfo->remaining = 10;
	struct timeval timeout = { 1, 0 };
	event_add(tinfo->tm_ev, &timeout);
}

int main()
{
	evbase_ctx = event_base_new();
	evhttp_ctx = evhttp_new(evbase_ctx);

	signal(SIGPIPE, SIG_IGN);

	evhttp_set_gencb(evhttp_ctx, request_cb, NULL);
	if (evhttp_bind_socket(evhttp_ctx, "0.0.0.0", 2345) < 0) {
		perror("failed to bind port 2345");
		exit(1);
	}

	printf("listening on port 2345\n");
	event_base_loop(evbase_ctx, 0);
	// CTRL-C will send SIGINT and terminate the process
	return 0;
}
```

compile and run with something like:

```
gcc --std=c99 -Wall -o evhttp_stream evhttp_stream.c -levent
./evhttp_stream
```

test with curl:

```
curl -v localhost:2345/
```

watch as curl gets a chunk of the response each second.

So, if you're literally calling `sleep()`, or you're calling `evhttp_send_reply_chunk()` in a loop, you can't do that in an event-based application. You need to schedule a callback to happen later. Nothing works while your function is running, only in between your functions.

The tricky part in this case is, how do you know when the client has downloaded most of the previous chunks, so it's a good time to write another chunk? That is more complicated. I *think* you could call `evhttp_request_get_output_buffer()` and check how much data is still in that buffer, and then decide to write more now, or sleep for a fraction of a second and check again. This is obviously not an optimal pattern, just a hacky start ...

**Comment by Tyrant2010** [comment]
@ploxiln Thank you sir,  your code do work, Thank you again！

**Comment by mason-hale** [comment]
Thank you very much! That is extremely helpful, and I had trouble finding working examples online. Much appreciated.
