### ISSUE TITLE
incorrect DNS server added by default

### ISSUE THREAD

**Issue by ghazel** [libevent/libevent#569]
If `EVDNS_BASE_INITIALIZE_NAMESERVERS` is used in the construction of an `evdns_base`, on some systems (like Android), the bogus DNS server `127.0.0.1:53` will be added (see https://github.com/libevent/libevent/blob/master/evdns.c#L3651 ).

I know it's difficult to keep up with all the random ways to fetch DNS servers, but calling code effectively can't use `EVDNS_BASE_INITIALIZE_NAMESERVERS` without *also* checking for `resolv.conf` and parsing it to know that `127.0.0.1` won't be incorrectly inserted.

**Comment by azat** [comment]
Seems that android doesn't updates `$PREFIX/etc/resolv.conf`, does it a problem not to call it with `EVDNS_BASE_INITIALIZE_NAMESERVERS` or are you talking about 3-d party apps here?

Personally I don't like the idea of adding 127.0.0.1 automatically, though there can be such users already who depends from this behavior, so I guess that we have to introduce yet another option, like `DNS_OPTION_NO_DEFAULTS`, instead of removing this code completely.

P.S. and it should be (https://github.com/libevent/libevent/blob/master/evdns.c#L4186)[this line] instead of L3651
