### ISSUE TITLE
wrong size of size_t

### ISSUE THREAD

**Issue by themaddoctor** [libevent/libevent#580]
source 2.1.8, built on a 64-bit system.
This cannot be right:
grep SIZE_T /usr/include/event2/event-config.h 
#define EVENT__SIZEOF_SSIZE_T 8
#define EVENT__SIZEOF_SIZE_T 4

When building firefox, the build choked at the point where it verifies the sanity of the sizes defined in this header.

**Comment by ploxiln** [comment]
`event-config.h` is generated at build time.
On my x86_64 macOS 10.12 system, it just contains `#define EVENT__SIZEOF_SIZE_T 8`, no `SSIZE_T` ...

**Comment by azat** [comment]
@themaddoctor what os do you have?

**Comment by themaddoctor** [comment]
linux, kernel 4.12.4, glibc 2.26, gcc 7.1.0

I ran a little test program, and the size should be 8.

**Comment by ploxiln** [comment]
I did a build from source on linux 4.4 with gcc 5.4 and get the same result I got before (just `SIZE_T 8`). I suspect this has to do with autoconf or cmake.

Are you sure that `event-config.h` is from libevent-2.1.8? (It's in that header as`EVENT__VERSION`). Do you know how it was built and installed?

**Comment by themaddoctor** [comment]
tar -xf libevent-release-2.1.8-stable.tar.gz
cd libevent-release-2.1.8-stable
cmake -DEVENT__BUILD_SHARED_LIBRARIES=ON -DCMAKE_INSTALL_PREFIX=/usr
make
make test
make install
cd ..
rm -rf libevent-release-2.1.8-stable
strip -S build/usr/lib/*
mv build/usr/lib/libevent* /usr/lib64/

/* Numeric representation of the version */
#define EVENT__NUMERIC_VERSION 0x02010800
#define EVENT__PACKAGE_VERSION "2.1.8"

#define EVENT__VERSION_MAJOR 2
#define EVENT__VERSION_MINOR 1
#define EVENT__VERSION_PATCH 8

/* Version number of package */
#define EVENT__VERSION "2.1.8-beta"

I hate cmake, btw. How do you do it with gnu config tools?

**Comment by ploxiln** [comment]
yeah, I just use `./configure ... && make ...` (that's the gnu autotools system), I think cmake support is somewhat "beta" in libevent

**Comment by themaddoctor** [comment]
Well, the configure script is missing from the latest source package, and there is no bootstrap.sh script. Kind of lousy to do that if cmake support is only beta.

**Comment by ploxiln** [comment]
`configure` is present in the tarball which the libevent.org homepage links to: https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz

**Comment by themaddoctor** [comment]
Another reason to hate cmake. This problem (and another) went away after rebuilding from the other tarball.

**Comment by azat** [comment]
Hi @themaddoctor ,

Just fixed `EVENT__SIZEOF_SIZE_T` for cmake (and the reason was -- typo).

> Well, the configure script is missing from the latest source package

where did you get that source package?

there are two options:
- [release](https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz)
- [archive of the tag that generated by github](https://github.com/libevent/libevent/archive/release-2.1.8-stable.tar.gz)

The later does not have `configure` in it because we don't put it git (since it is pretty odd thing to do), but I agree that it is confusing (if you get the release from [releases](https://github.com/libevent/libevent/releases) not from the [libevent.org](http://libevent.org/))

> and there is no bootstrap.sh script

there is `autogen.sh` (and this is kind of standard for projects with autoconf) plus there is a [note](https://github.com/libevent/libevent#autoconf-1) in `README`

> Kind of lousy to do that if cmake support is only beta.

Didn't understand this bit.

**Comment by ploxiln** [comment]
> Kind of lousy to do that if cmake support is only beta.

He was confused about the missing `configure` script in the tarball he downloaded - he thought it a bad idea to omit `configure` while the cmake setup for libevent is "somewhat beta" (what I called it, above).

I think this is all down to downloading the wrong tarball. For what it's worth, the github release page does have a link to to the "correct" tarball which includes configure, it's the top link ... there's just also the automatic-from-git-tag tarball link below it, which is the "wrong" one. So I think there's nothing to do about this, it's just some bad luck and confusion.
