### ISSUE TITLE
Issues with libevent, Capsicum, and the global namespace

### ISSUE THREAD

**Issue by lattera** [libevent/libevent#601]
I'm [working](https://trac.torproject.org/projects/tor/ticket/17521) on Capsicum support in Tor. I've got it nearly completed. However, when debugging an issue with transparent proxy mode, I discovered that libevent uses `socket(2)` directly. This prevents transparent DNS support in Tor from working.

I wonder if we could teach libevent to accept callbacks for accessing the global namespace (ie, `socket(2)` and friends). I could pass a function, say `sandbox_socket`, that wraps around `socket(2)` in a Capsicum-safe manner.

**Comment by azat** [comment]
I need to take a deep look into this capsicum thing, and once I will finish with this, I will get back to you.

**Comment by lattera** [comment]
It also appears that libevent wants to open `/etc/resolv.conf`. Without providing abstraction APIs for opening file descriptors (and sockets), several features of Tor when Capsicum is enabled are broken (relay mode and transparent proxy mode).

The scope of this issue should be expanded to any call that accesses global namespace, not just sockets.

**Comment by lattera** [comment]
Any updates?

**Comment by azat** [comment]
Hi @lattera 
Thanks for pinging me!

So I just looked through the capsicum and the differences between seccomp.
(also just out of curiosity I cloned `https://github.com/lattera/tor hardening/cpasicum` and take a look)

Right now I don't have to implement this, but if you can contribute such functionality I wouldn't be against this.

I have some thoughts in mind about this:
- we already have allocator interceptions (see `event_set_mm_functions()`), this can be implemented in the same way
- it should have some switch to turn it off during compilation (like `EVENT__DISABLE_MM_REPLACEMENT` for allocator interceptions)
- it should as inconspicuous as possible (since we already have a lot of complexity and enormous test matrix)
- and it should have some tests of course (though this is pretty simple)

And sorry for the huge delay

P.S does tor allocates a lot of fds? If so, wouldn't UUID generation/lookup (O(1)) will be a problem? BTW why fd needs UUID attaching? But this is off topic of course.
P.P.S it would be great if there will be some ability to change caps for the childs in capsicum, but I guess this has some security issues/concerns.

**Comment by azat** [comment]
@lattera I'm going to close this, due to no interest, feel free to reopen once you will have get back to this!
