### ISSUE TITLE
my read callback does get called sometime

### ISSUE THREAD

**Issue by aliahaider** [libevent/libevent#642]
I have a multithreaded application where each thread creates its own bufferevent and a separate socket to talk to another server application over tcp.  
The bufferevent_write on the server side never fails.
But read callback on the client side some time does not get invoked.
On the server side after each bufferevent_write I also do bufferevent_flush after checking that bufferevent_write is successful.
I am using evthread_use_windows_threads() and BEV_OPT_THREADSAFE.
I have noticed that adding a delay after each send on server side that is after bufferevent_flush helps and my read callback gets invoked most of the time but once in a while I still see the problem even with the delay.
I do not know how to debug this isssue at this point and need help debug it.

Thanks!

**Comment by azat** [comment]
On Mon, Jun 11, 2018 at 08:50:10AM -0700, aliahaider wrote:
> I have a multithreaded application where each thread creates its own bufferevent and a separate socket to talk to another server application over tcp.  
> The bufferevent_write on the server side never fails.

Because all it is do, is adding the data to the internal buffer, it does
not send data *right now*.

> But read callback on the client side some time does not get invoked.

Are you sure that data received by the server?  Can you attach a
reproducer? Or maybe some network traces? (looks like you have win32,
maybe wireshark or smth like this)

> On the server side after each bufferevent_write I also do bufferevent_flush after checking that bufferevent_write is successful.

flush() is a no-op for bufferevent_sock/iocp-bufferevent

> I am using evthread_use_windows_threads() and BEV_OPT_THREADSAFE.

Good.

In a nut shell:
- you should use evthread_use_windows_threads() only if you access base
  from multiple threads, and this is not a good pattern to use in a long
  term, it is way more better to have base-per-thread.
- you need BEV_OPT_THREADSAFE only if you access bufferevent from
  multiple threads

But do not remove this until we will resolve this issue please.

> I have noticed that adding a delay after each send on server side that is after bufferevent_flush helps and my read callback gets invoked most of the time but once in a while I still see the problem even with the delay.

This paragraph + the part about bufferevent_flush() sounds like you
assume that after bufferevent_flush() you think that all data was
written to the socket, while this is not true.

If you need this behaviour you have to implement this in your protocol.

The simplest way I see to achieve this is add length of the payload at
start and read from the socket until the whole payload will be read.

> I do not know how to debug this isssue at this point and need help debug it.

Also there is debug logging, although it is too verbose (and it could be
turned off during compiling libevent, you should check that it is
enabled first):
  event_enable_debug_logging()


But maybe I'm missing something, in this case I need more info, traces
e.t.c.

**Comment by aliahaider** [comment]
Hi Azat:
Thanks for looking into the issue, your comments and tips to debug the issue. 
I found the root cause of the issue,
The read callback in the client code was written to process only one message at time from the server as the server code sends two messages separately at different times (but pretty close to each other in time) for each request it receives from the client.
Once in a while when messages are small multiple messages are received together from the server on the socket and moved into libevent input buffer. 
The read callback was called but it was not draining the input buffer completely hence never processed the other messages sent by the server.
Once I figured that out and changed the code it seems to be working.
