### ISSUE TITLE
Need native build for Windows

### ISSUE THREAD

**Issue by pprindeville** [libevent/libevent#655]
From what I can tell, the appveyor.yml file suggests that builds are done via mingw32.

Could we do native builds under VisualStudio as well?

**Comment by azat** [comment]
There is cmake build, which uses VS only:
  https://github.com/libevent/libevent/blob/master/appveyor.yml#L57

Also I use next vagrant setup to built in windows, and it also works fine:
  https://github.com/libevent/libevent/blob/master/Vagrantfile#L376
(This one even passes all tests, from time-to-time)

Why are you interested? I'm curious because afaik you don't built for
windows, but if I'm wrong that will be great, since I wouldn't like any
help here (maybe you can run/automate/enhance-to-kvm-images those vagrant
boxes)

Refs: http://archives.seul.org/libevent/users/Aug-2018/msg00000.html

**Comment by pprindeville** [comment]
> Why are you interested? I'm curious because afaik you don't built for windows [...]

I don't build for Windows, no, but I work on software that uses libevent and runs on Windows and I need to make sure I'm not breaking anything for the user base...

**Comment by pprindeville** [comment]
BTW, what would be involved in adding and supporting a `.vcproj` file (or whatever VS2015 and later uses)...

**Comment by ploxiln** [comment]
cmake can generate a visual studio project
https://cmake.org/cmake/help/v3.10/manual/cmake-generators.7.html#visual-studio-generators

**Comment by pprindeville** [comment]
Okay... I wonder how many developers use `cmake` and how many use `vs` only.

**Comment by pprindeville** [comment]
What about shipping libevent with all of the `.vcxproj` files included?  Then even Visual Studio developers who don't have CMake could build it...

**Comment by azat** [comment]
I'm not totally against this idea, but this files should be added *only into* release *tarballs*.

P.S. in my memory you was the only one who was asking about this, so maybe this doesn't worth it?
