### ISSUE TITLE
how to insure Sync for one evhttp_connection in different threads?

### ISSUE THREAD

**Issue by ww1999520** [libevent/libevent#713]
I'm trying to use your evhttp mudule,but i find the problem,u design it for dealing request in net io thread,but our request from client need much to dispose.avoid blocking all the net io threads, i try to post a complete request to another thread .but when i read the codes in http.c,i find that,u haven't disign a atomic counter nor a lock for evhttp_connection, is it won't be core dump in muilt threads?

the structure bufferevent hase locker and counter,why not evhttp?

**Comment by azat** [comment]
I guess the answer will be that it wasn't intended for such use case, however until you call `evhttp_send_reply()` (or the same api for chunked callbacks) it should not access your connection/request.

Although there was some issues with this, so you need at least next patches:
- 306747e51c1f0de679a3b165b9429418c89f8d6a
- 99d0a952dada771b91acf63f5208b994e80a2986
- 5ff8eb26371c4dc56f384b2de35bea2d87814779
*Thay do not included into any stable release yet*

So if you libevent version contains them then it should work for your use-case.

But maybe it will be better to use libevhtp for this (personally I would stick with libevent if you need pretty simple functionality and with libevhtp otherwise).

**Comment by ww1999520** [comment]
thank u,i will try to build iocp mode http server base on buffevent of libevent and http-parser, your libevent is really helpfull,thank u again....

**Comment by azat** [comment]
>
> thank u,i will try to build iocp mode
>

For iocp you need upstream (major bugs had been fixed just recently)

See #709 for details

**Comment by ww1999520** [comment]
sorry,i didn't describe my question clearly...I tried evhttp in iocp mode yesterday.
the read callback works.but i considered the evhttp_connection  structure has no lock or aotimic counter ,iocp module is in muilt thread,if code running in http read back fuction and cost much time,but the client close the socket,then http error cb wake up in another iocp thread,then maybe a disabled pointer will be read or writen by the read call back thread......this is why i ask this quetion at the beginning
