### ISSUE TITLE
what's the different between the released packages

### ISSUE THREAD

**Issue by bi-kai** [libevent/libevent#717]
hi, what's the difference between those two packages:
1. libevent-2.1.8-stable.tar.gz
2. Source code(tar.gz)

**Comment by azat** [comment]
If you are talking about [this](https://github.com/libevent/libevent/releases/download/release-2.1.8-stable/libevent-2.1.8-stable.tar.gz) and [this](https://github.com/libevent/libevent/archive/release-2.1.8-stable.tar.gz) then:

>libevent-2.1.8-stable.tar.gz

is the dist archive that created with `make dist`, i.e. it does not requires from you to run `autogen.sh` (and related stuff), since it contains `configure` cache

>Source code(tar.gz)

is the copy of the repository, automatically created by github (i.e. `git archive -p libevent.tgz`)
