### ISSUE TITLE
nmake files on vs2013 to support pthread

### ISSUE THREAD

**Issue by shisg1002** [libevent/libevent#718]
hello,
  I want to use libevent in win32 whit pthread , but i don't know how to compile.  I use nmake to compile proj. I need some good advice, thanks. (My English is not good, If you don't understand, please leave me a message -. - )

**Comment by azat** [comment]
Hi!

pthread is POSIX and windows is not POSIX compatible.
Although AFAICS you can use pthreads (I guess it is some kind of wrapper) from [mingw](https://stackoverflow.com/a/792142/328260).
Something like for [setup the system](https://github.com/libevent/libevent-extras/blob/master/Vagrantfile#L331-L364) and to compile [libevent](https://github.com/libevent/libevent-extras/blob/master/Vagrantfile#L387-L394).

But I would suggest you using POSIX compatible OS instead of windows if you need pthreads (although I'm not sure about it)

**Comment by shisg1002** [comment]
Thanks for reply me!
I have a program written by another guy on linux with libevent,
now,  i must move it from linux  to windows, and I don't have much time to modify the frame of the prog. So, it's a lot of trouble.
Now the most serious problem is:
I find my prog send msg success, and client do reply, but the callback func does be called. Tcp link is ok, i catch the reply packege on the net. I can't locate the problem. 
So I wonder if it's because libevent don't support pthread on windows.
A little more advice please~ so nice of you! :P
