### ISSUE TITLE
Failed to create event base when anti-virus blocking INADDR_LOOPBACK

### ISSUE THREAD

**Issue by timfuze** [libevent/libevent#724]
Currently I am using libevent for socket read/write/timeout event only and when I create event base in windows, some users are experiencing application failure due to anti-virus/firewall blocking libevent binding localhost (127.0.0.1).   Is there a way we can avoid this other than asking user to disable anti-virus?

**Comment by azat** [comment]
The root cause of this is `evutil_ersatz_socketpair_()` that emulates `socketpair` on win32.

And it is called unconditionally from `win32_init()` (for signals), although it is allowed to fail, but I guess that antivirus would terminate/report the program anyway.

Thinking about this we have next options:
- some switch for this to avoid this AF_INET bind -- don't like this idea, too many switches, inreases test matrix
- **replace that AF_INET bind with something else**
- [win10 AF_UNIX support](https://blogs.msdn.microsoft.com/commandline/2017/12/19/af_unix-comes-to-windows/) (but I did not look through the whole paper, just the title)

P.S. the second place where we need internal socketpair is for notifying event_base (`event_use_windows_threads()`)

**Comment by timfuze** [comment]
Thanks.  Looking at the code, it looks like it's the evthread_use_pthreads is the cause of failure when localhost is blocked (not the anti-virus throwing error).

> event_base_new_with_config: Unable to make base notifiable.

**Comment by azat** [comment]
>if I set EVENT_BASE_FLAG_NOLOCK, then it would skip this code that causing the failure
Only the second one, there still will be the pipe for signals (like I wrote in the first comment), and you cannot skip that.
So if "antivirus" terminated/stops/aborts the program once it detects listen/bind this will not work. 

>What would be the way to work with EVENT_BASE_FLAG_NOLOCK?
No, but I would suggest you rethink your architecture to use base per thread (but I do understand that this can be too hard/long-term).

**Comment by timfuze** [comment]
@azat , thanks.  I decided to take a look at the alternative architecture so that event model becomes more flexible.

**Comment by zengqu** [comment]
Currently when i use libevent in my program, i got the same error, How can i reproduce this scenario on my computer.
anti-virus/firewall blocking libevent binding localhost (127.0.0.1).

**Comment by sfhacker** [comment]
This issue is from 2018!
