### ISSUE TITLE
Event_base_dispatch bloking main thread!

### ISSUE THREAD

**Issue by frknyldz** [libevent/libevent#729]
Hi, i am trying to start event base loop in another thread and then after some time I eventually try to exit the loop from main thread. I tried to add a while loop isRunning and call event base loop with EVLOOP_NONBLOCK flag but this solution uses more cpu resources. How can I start the loop async and be able to break the event loop if so?

**Comment by azat** [comment]
Hi!

>Event_base_dispatch bloking main thread!

Of course it does

>start event base loop in another thread and then after some time I eventually try to exit the loop from main thread

so your next actions means that you tried this but this does not work?
Have you enabled thread support?
- `evthread_use_ptheads()` for linux
- `evthread_use_windows_threads()` for windows

>I tried to add a while loop isRunning and call event base loop with EVLOOP_NONBLOCK flag but this solution uses more cpu resources.

Indeed, since you do not know when you can sleep (and how long), hence you have to call dispatch again and again, even if there is no events pending, IOW this became busy loop.

>How can I start the loop async and be able to break the event loop if so?

Try to enable thread support for `event_base` (see above).

P.S. please do not use such screaming headlines

**Comment by frknyldz** [comment]
Hi,
That wasnt a scream, i figured out . I think my problem was 'condition variable' stateless behaivor. Because when i called loop exit from another thread the signal reaching to cond but no action happened. When i try it something like that;
`while(!isStopped)
{
event_loop_exit()
}` in destructor and set isStopped to true after `event_loop_dispatch()` that works fine. And when i watch while loop with a counter it exited after few times trying(different results every time). But anyway thanks for your reply, I used your advice too.

**Comment by azat** [comment]
> Because when i called loop exit from another thread the signal reaching to cond but no action happened.

How did you checked it?
And which cond had been signaled?

> When i try it something like that;
while(!isStopped) { event_loop_exit() } in destructor

If you meant `event_base_loopexit()`, that it just schedules one more request and once it will be reached event loop will be exit, IOW it should work if it doesn't then there is a problem and you should not solve it with the loop.

There is `event_base_loopbreak()` which will instantly break the loop (once current callback will be finished, or if no events is active it will notify the base by using internal pipe).

All above should and will exit/break the `event_base_dispatch()`/`event_base_loop()`

But if you are using `event_base_loop(EVLOOP_ONCE)` than it would not.

**Comment by frknyldz** [comment]
Hello, i tried something like that am i missing something ?
```c++
class ServerThread {
public:
    struct event_base* base;
    struct evhttp *http;
    bool isRunning = false;
    std::thread *t;

    void Start() {
        isRunning = true;
        t = new std::thread([&]() {
            event_base_dispatch(base);
            cout << "Loop exited" << endl;
            isRunning = false;
        });
    };

    void Stop() {
        int counter = 0;
        while (isRunning) {
            event_base_loopbreak(base);
            counter += 1;
        }
        cout << "Trying to exit " << counter << " time" << endl;
        event_base_free(base);
        evhttp_free(http);
    };

    ServerThread() {
        evthread_use_pthreads();
        base = event_base_new();
        http = evhttp_new(base);
        evhttp_bind_socket_with_handle(http, "0.0.0.0", 8080);
    };

    virtual ~ServerThread() {
        Stop();
        t->join();
        delete t;
    }
};
```
and the main is
```c++
int main(int argc, char** argv) {
    ServerThread server;
    server.Start();
    return 0;
}
```
Results :
Loop exited
Trying to exit 3120 time

Loop exited
Trying to exit 3830 time

Loop exited
Trying to exit 2604 time

**Comment by azat** [comment]
Here are some comments for your code:
- `std::atomic` for `isRunning` is good idea in general
- I don't see calls to `evthread_use_pthreads()` or something related
- `event_base_loopbreak()` tries to instantly break the loop, **but** if `event_loop_dispatch()` will be executed after it then it `event_base_loopbreak()` will not break the loop (since it just installs flag in the base, and in `event_loop_dispatch()` resets it at the beginning), you can use `event_base_loopexit() + event_base_loopbreak()` this should work even if loop is not started yet, but this will/can create problems if you will call `event_loop_dispatch()` again, since `event_base_loopexit()` schedules event, and if current loop will be exited by loopbreak, event from the loopexit will be processed during next loop invocation, hence next loop will exit instantly

Can you please post full reproducer?

**Comment by frknyldz** [comment]
Thanks for fast reply ,

- ` evthread_use_pthreads();` is in the ServerThread consturctor

- The results reduced with atomic, you are right
- I didnt understand "you can use `event_base_loopexit() + event_base_loopbreak()`" meaning

- Here is the full code 
```c++ 
#include <iostream>
#include <event2/event.h>
#include <event2/http.h>
#include <event2/thread.h>
#include <thread>
#include <atomic>


using namespace std;

/*
 * 
 */
class ServerThread {
public:
    struct event_base* base;
    struct evhttp *http;
    std::thread *t;
    std::atomic<bool> isRunning{false};

    void Start() {
        isRunning = true;
        t = new std::thread([&]() {
            event_base_dispatch(base);
            cout << "Loop exited" << endl;
            isRunning = false;
        });
    };

    void Stop() {
        int counter = 0;
        while (isRunning.load()) {
            event_base_loopbreak(base);
            counter += 1;
        }
        cout << "Trying to exit " << counter << " time" << endl;
        event_base_free(base);
        evhttp_free(http);
    };

    ServerThread() {
        evthread_use_pthreads();
        base = event_base_new();
        http = evhttp_new(base);
        evhttp_bind_socket_with_handle(http, "0.0.0.0", 8080);
    };

    virtual ~ServerThread() {
        Stop();
        t->join();
        delete t;
    }
};

int main(int argc, char** argv) {

    ServerThread server;
    server.Start();
   
    return 0;
}

**Comment by azat** [comment]
> I didnt understand "you can use event_base_loopexit() + event_base_loopbreak()" meaning

I'v [modified you program](https://gist.github.com/azat/b709865d0ad17ed79e39259aa731304a), and now it exit from the event loop without while loop, in this sample simple `event_base_loopexit()` will be enough, however 

So again:
- `event_base_loopexit()`  = `event_base_once(base.exit = true)`
- `event_base_loopbreak()` = `base.break = true`

And here simplified version of `event_base_dispatch()`:
- `base.break = false`
- `base.exit = false`
- `while (!base.break && !base.exit) { poll(); }`

So with `event_base_loopbreak()`:

```
T1:                                            T2:
                                                 event_base_loopbreak()
event_base_dispatch()            
< working, since the flag had been reset >
```

But with `event_base_loopexit()`:

```
T1:                                            T2:
                                                 event_base_loopexit()
event_base_dispatch()            
<got event from event_base_loopexit() - set `base.exit`>
check `base.exit` - exit
```

So in you case you can simply replace `event_base_loopbreak()` with `event_base_loopexit()` and that is it.

(But be aware of caveats that can be popped up in case you will run `event_base_dispatch()` again for the same base if event from the `event_base_loopexit` had not been processed during this loop invocation)

And the reason why you may be interested in both, because `event_base_loopexit()` exit via event, and that said that there can be cases when event loop will prefer handling other events over event from `event_base_loopexit()` (but if you will install max_dispatch to 1, then you will not need `event_base_loopbreak()` anymore)

**Comment by azat** [comment]
> Is there a way for free these when shutting down ?

libevent_global_shutdown() will free those objects.
