### ISSUE TITLE
Messy and clashing content of libevent* libraries

### ISSUE THREAD

**Issue by kloczek** [libevent/libevent#732]
Looking on Makefile.am 
```
libevent_la_SOURCES = $(CORE_SRC) $(EXTRAS_SRC)
libevent_la_LIBADD = @LTLIBOBJS@ $(SYS_LIBS)
libevent_la_LDFLAGS = $(GENERIC_LDFLAGS)

libevent_core_la_SOURCES = $(CORE_SRC)
libevent_core_la_LIBADD = @LTLIBOBJS@ $(SYS_LIBS)
libevent_core_la_LDFLAGS = $(GENERIC_LDFLAGS)
        
if PTHREADS
libevent_pthreads_la_SOURCES = evthread_pthread.c
libevent_pthreads_la_LIBADD = $(MAYBE_CORE)
libevent_pthreads_la_LDFLAGS = $(GENERIC_LDFLAGS)
endif
        
libevent_extra_la_SOURCES = $(EXTRAS_SRC)
libevent_extra_la_LIBADD = $(MAYBE_CORE) $(SYS_LIBS)
libevent_extra_la_LDFLAGS = $(GENERIC_LDFLAGS)

if OPENSSL
libevent_openssl_la_SOURCES = bufferevent_openssl.c
libevent_openssl_la_LIBADD = $(MAYBE_CORE) $(OPENSSL_LIBS)
libevent_openssl_la_LDFLAGS = $(GENERIC_LDFLAGS)
libevent_openssl_la_CPPFLAGS = $(AM_CPPFLAGS) $(OPENSSL_INCS)
endif
```
I see that libevent is equivalent of the libevent_core + libevent_extra, and libevent_openssl and libevent_pthreads is linked to libevent_core.
Problem is that at the moment most of the public projects is using only libevent.
If someone will want to use libevent_pthreads or libevent_openssl it will cause linking symbols clash bacause libenebt and libevent_core will be providing exactly the same symbols.

**Comment by azat** [comment]
> I see that libevent is equivalent of the libevent_core + libevent_extra, and libevent_openssl 

This should be deprecated a long time ago, IOW it not safe to link with it, since they can be removed in future releases (although if you use pkg-config you are safe)

> Problem is that at the moment most of the public projects is using only libevent.
If someone will want to use libevent_pthreads or libevent_openssl it will cause linking symbols clash bacause libenebt and libevent_core will be providing exactly the same symbols.

And what the problem with linking with both, e.g. `event_pthreads` (hence `event_core` implicitly) and `event_core` explicitly?

You will find this variety range of libraries, for example qt (almost every qt library is linked against qtcore).

See #142 for debates about linkage rework
