### ISSUE TITLE
Request a new release or pre-release

### ISSUE THREAD

**Issue by YihaoPeng** [libevent/libevent#744]
I am being troubled by this issue in my project (https://github.com/btccom/btcpool/issues/75): [#512: Deadlock happend](https://github.com/libevent/libevent/issues/512).

I know that the code in master branch has fixed this issue. This issue has never happened in my project since the master branch of libevent was used.

However, the master branch of libevent keep changing (Maybe some new issues will be introduced. This may not be safe for online services).

And the latest release `release-2.1.8-stable` is too old and has been confirmed to have this issue. So I don't have a stable version of libevent that works fine with my project.

Can you consider making a release or pre-release in the near future? After all, libevent has no new release in two years.

**Comment by azat** [comment]
> Can you consider making a release or pre-release in the near future?

Indeed, I was going to make the release on new year holidays, but I didn't have enough time for this (due to sickness). And since there is interest, I will try to make it on this weekends.

> After all, libevent has no new release in two years.

Namely, we definitely need to make releases more often, time is the lacking resource though.

> My humble suggestion is to release betas of patch releases

Sounds good, I will take a look at the diffstat/patches/tests and decide will it be beta or stable.

Thank you for the reminder!

**Comment by azat** [comment]
So both 2.1.x (9c75c24) and 2.0.x (4294867) had been released, please go out and test (and get back once you will find something odd)!
