### ISSUE TITLE
evbuffer_chain_align may cause memory problem

### ISSUE THREAD

**Issue by huxiang44** [libevent/libevent#748]
here the length to move is chain->off, which includes misalign and actual data. i think only the actual data need to be moved, and the src destination may overflowed (chain->misalign + chain->off).
memmove(chain->buffer, chain->buffer + chain->misalign, chain->off);

**Comment by huxiang44** [comment]
encounter a coredump when doing memcpy after calling evbuffer_chain_align.
#0  0x00007fcf65059681 in memcpy () from /lib64/libc.so.6
#1  0x000000000044ca6d in evbuffer_add (buf=0x7fcf57738490, data_in=0x7fcf64bd2c00, datlen=5) at buffer.c:1591
.....
here the memcpy statement is 
memcpy(chain->buffer + chain->off, data, datlen);
should it copy data to the new off position. i think chain->off should be updated after  evbuffer_chain_align.

**Comment by azat** [comment]
Which version of libevent do you use? (if you are building it from sources, then please attach commit sha)
Also maybe you can run it under valgrind/ASAN (compile with `-fsanitize=address`) ?

> currently, the struct chain is

This is interesting, to g out-of-bound and corrupt `chain`, it's address should be after `chain->buffer` and not far away, this is possible, but is this true?

**Comment by huxiang44** [comment]
Thanks for reply！
The package is libevent-2.0.22-stable.tar.gz. It is directly downloaded from this website. Sorry to tell you that no commit sha can be provided. This problem is extremely rare. I doubt it can be easily reproduced. The stack is real for sure and so are the variables. :)
The problem is possibly caused by memmove or memcpy. I test two cases, both can lead to coredump.
1.void * memmove ( void * destination, const void * source, size_t num ) : a large value of num
2.void * memcpy ( void * destination, const void * source, size_t num ): a large offset value of  destination
Both cases can access addresses out of memory allocated.
Further, the value chain->misalign is wrong apparently, because evbuffer_chain_should_realign will reset it to zero. But it's not. I think the mistaken memory operations may lead this. But cannot explain the details. ><
i may try valgrind, not sure of finding anything useful. Any other suggestions.

**Comment by huxiang44** [comment]
a mistake above. should be evbuffer_chain_align

**Comment by azat** [comment]
> libevent-2.0.22

There was some fixes for evbuffer
- #335 
- f4b28a6c70a37d0e27f4d067a49b0be0616c23d8
- 90ae4c5013032158bafad41279823d90eec4d206 (`evbuffer_add_file()` only)

But AFAICS this is different.

Can you try latest libevent from sources and verify that the bug is still there?

> This problem is extremely rare

hourly, daily, monthly?

> value chain->misalign is wrong apparently

Maybe you have some buffer-overrun/invalid-write in your program, that corrupts internal evbuffer stuff. It is possible, but cannot say how likely it is.

> Any other suggestions.

You can compile your program with `-fsanitize=address` (for this it is better to use latest compiler, gcc or clang)

**Comment by huxiang44** [comment]
yep, these fixes seems irrelevant. but thanks.
The problems is caused by frequent requests to connect from our database cluster to the outside server where data source resides. Due to some reason not known currently, the connection is not built successfully. But the script is run in a loop for many times. As a result, every connection to the server need to add some data to the event buffer. This problem has not occurred before since these two or three years. So i typed "this problem is extremely rare". Your suspicion of buffer-overrun may be a reasonable cause. But it seems hard to confirm this. May the only way to debug this is using some memory debug tool as you have suggested.

**Comment by huxiang44** [comment]
memmove(chain->buffer, chain->buffer + chain->misalign, chain->off);

**Comment by huxiang44** [comment]
memmove(chain->buffer, chain->buffer + chain->misalign, chain->off);

**Comment by huxiang44** [comment]
But should the code be written like this:
In evbuffer_chain_align:
memmove(chain->buffer, chain->buffer + chain->misalign, chain->off - chain->misalign);
and set chain->off to the new value:
 chain->off -=chain->misalign

**Comment by azat** [comment]
> memmove(chain->buffer, chain->buffer + chain->misalign, chain->off - chain->misalign);
> chain->off -=chain->misalign;

Have you tried it?

- misalign -- unused space at the beginning of buffer
- off -- offset into `buffer + misalign` at which to start writing

So for `misalign>off` (and this can be true, easily), you changes will run out-of-bound (because of unsigned from negative value)

And needless to say that `evbuffer_chain_align()` looks right to me, it shift the buffer to free some unused space for further use.

**Comment by azat** [comment]
> May the only way to debug this is using some memory debug tool as you have suggested.

valgrind is pretty slow (since it emulates everything), but ASAN (`-fsanitize=address`) is not that bad, that said that if you do not need enormous performance from you application (or you can run multiple instances of them) you can compile your app with ASAN and run it even in production (but be aware that it needs huge virtual memory chunk).

You can read more about them here:
- https://clang.llvm.org/docs/AddressSanitizer.html
- https://github.com/google/sanitizers/wiki/AddressSanitizer

**Comment by huxiang44** [comment]
thanks for explanation in details. I misunderstand the meaning of the variable off. The suggestion of using ASAN sounds great. Need more study onto it.

**Comment by azat** [comment]
@huxiang44 I'm going to close this for now, but please reopen (or open a new one if the problem will be in another bit) once you will have details!
