### ISSUE TITLE
Regression test failures on MacOSX for latest trunk

### ISSUE THREAD

**Issue by emmenlau** [libevent/libevent#749]
I build libevent latest trunk on MacOSX 10.11 with XCode (Apple clang 8.0.0). In the verify-step, a few regression tests are failing. Should I worry about them, or is it save to use libevent nonetheless? What can I do to help debug the issues?
See https://pastebin.com/h1BKx5zg for the verify report.

From the report next test has been failed:
- [x] http/read_on_write_error
- [x] dns/bufferevent_connect_hostname_emfile

**Comment by azat** [comment]
This is pretty bad (but I'm pretty sure that this is not that easy to trigger, plus this is http layer, so you should be fine if you do not use it):
>   FAIL /Users/user01/builds/b65d6781/0/libevent/test/regress_http.c:4079: assert(req)[err] evhttp_read_cb: illegal connection state 0
>  [bufferevent_connect_hostname_emfile FAILED]

This should be false-positive:
>  FAIL /Users/user01/builds/b65d6781/0/libevent/test/regress_dns.c:1309: assert(be_outcome[3].dnserr == default_error): 8 vs 11
 > [bufferevent_connect_hostname_emfile FAILED]

Will take a look later this week.
Thanks for the report!

**Comment by azat** [comment]
> assert(be_outcome[3].dnserr == default_error): 8 vs 11

So here is what this errors means:
```c
#define EAI_SYSTEM -11
#define EAI_SERVICE -8
```

So it means that it cannot resolve `service` from `getaddrinfo()`, maybe it cannot open `/etc/services` and report `EAI_SERVICE` instead of `EAI_SYSTEM`, looks like it is, since our travis-ci also [reports](https://travis-ci.org/libevent/libevent/jobs/478709863#L1145) this error

**Comment by emmenlau** [comment]
I'm not sure if this is related, but the file `/etc/services` is world-readable:
```
#> ls -la /etc/services
-rw-r--r-- 1 root wheel 677972 Feb 25  2016 /etc/services
```

**Comment by azat** [comment]
> /etc/services is world-readable

This test is not about reading `/etc/services`, it is about how `bufferevent_connect_hostname()` will react when there is no more file descriptors available, since it adjust `RLIMIT_NOFILE` in that way, to fail any next file/socket allocation.

So when `getaddrinfo()` tries to read `/etc/services` it got EMFILE, and expected value is how it should react.

Can you post output of `dtruss regress --no-fork dns/bufferevent_connect_hostname_emfile` ?

**Comment by emmenlau** [comment]
Sorry, my CI system makes running `dtruss` virtually impossible :-( Is there something else I can try?

**Comment by azat** [comment]
I already started my vm, and got dtruss output by myself, so I will verify this and fix the assert once I will confirm it

Thanks for the report one more time!

**Comment by azat** [comment]
I've just pushed the last fix for this problems, can you verify that the same works for you?

**Comment by emmenlau** [comment]
Thanks a lot @azat ! I confirm the fix works on MacOS and tests go through now!
