### ISSUE TITLE
evbuffer_drain & evutil_closesocket 

### ISSUE THREAD

**Issue by danielstock** [libevent/libevent#753]
when i begin to cleanup the client connection, 
i call bufferevent_disable() to disable the events.

then i would call evbuffer_drain()  and evutil_closesocket(),
which one should be called first, drain or closesock?

**Comment by azat** [comment]
> then i would call evbuffer_drain() and evutil_closesocket(),
> which one should be called first, drain or closesock?

Suppose you have orthodox event-driven application:
- you are using one `event_base` per thread (or you have just one main thread in your application, someone can say 0 threads, but this is not true)
- if you have multiple threads, you call `bufferevent_*` only from that thread, which runs event loop for those bufferevents

In this case it does not really matter whether you will close or drain first, since none of code will be triggered in-between.
If you do not obey rules above, then I would say it is better to close first, but you will not see the difference I would say (but some libevent code can be triggered in this case).

Also, I imply that you do have `bufferevent_setfd(bev, -1)` call after `close(bufferevent_getfd(bev))`, right?

**Comment by danielstock** [comment]
@azat   thanks. the following is my program's main structure:
the program has multiple working threads, each with its own event_base.
and I pre-allocated thousands of client-context objects for each thread. I called bufferevent_socket_new for each object, using the thread's evbase as parameter.
once a connection is established, I select one thread(based on round robin algorithm),  and find one available client-context object for the connection. 
when the connection is disconnected, or other error occurs,  the client-context object would be released, and put back to free-list of the thread.
eventually, the client-context object could be re-used in the future.

so what's the proper order to cleanup the object? 
close_socket
bufferevent_setfd(bev, -1)
disable_buffer_event
evbuffer_drain

**Comment by azat** [comment]
> so what's the proper order to cleanup the object?
> close_socket
> bufferevent_setfd(bev, -1)
> disable_buffer_event
> evbuffer_drain

I would make it next way (although your sequence will work too):
- `bufferevent_disable()`
- `bufferevent_setfd(-1)`
- `shutdown()`
- `evutil_closesocket()`
- `evbuffer_drain()`

Also note that output/input evbuffer can be freezed (`evbuffer_freeze()`), and the `bufferevent_setfd()` should unfreeze it (at least for plain bufferevent socket) before you will call drain, so `bufferevent_setfd()` should goes before `evbuffer_drain()`

And do not forget to check exit codes, since sometimes consequences can crucial (for example in case if you put `evbuffer_drain()` at the beginning without checking exit code, and for freezed buffer it will fail).

**Comment by danielstock** [comment]
@azat   
does the bufferevent_setfd(-1)   unfreeze the input/output evbuffer automatically? 
or should i  manually call evbuffer_unfreeze()  before evbuffer_dran?

**Comment by azat** [comment]
You should not call it manually, but you should check the return value of the `evbuffer_drain()`

**Comment by danielstock** [comment]
@azat  if the return value of the evbuffer_drain() is -1(failure),  i should re-create (bufferevent_socket_new) the bufferevent  next time the client-context object (in which buffervent is contained) is re-used.

i wonder maybe it's better not to re-use the bufferevent,  just re-create it everytime the connection is established. 
but the efficiency might be lower when the client numbers are huge.

**Comment by azat** [comment]
> if the return value of the evbuffer_drain() is -1(failure), i should re-create (bufferevent_socket_new) the bufferevent next time the client-context object (in which buffervent is contained) is re-used

I would say that the program should fail if drain fails (in this particular case)

> i wonder maybe it's better not to re-use the bufferevent, just re-create it everytime the connection is established.
but the efficiency might be lower when the client numbers are huge.

Well, I think that you won't see a lot of difference in benchmarks if you will always recreate them

But if you are really curious, than you should do your own benchmarks anyway (since in don't know that much about your program)

**Comment by danielstock** [comment]
@azat   thanks.  yet there's another question.
i have one thread which loops through all the connection objects,  checking for user-defined errors (example:  long time no login request, too many bad packets, etc). 
i would close the connection if i find one. 

so, what's the proper way to close it?
would it be alright if i shutdown the socket to trigger socket_event,  then the buffer_event_callback  could do the cleanup work

**Comment by azat** [comment]
I do not think that closing the socket is a good idea, so I would recommend one of the following:
- `bufferevent_trigger_event(bev, BEV_EVENT_ERROR, 0)` to trigger `BEV_EVENT_ERROR` manually
- `bufferevent_free(bev)` to clean it up

**Comment by danielstock** [comment]
@azat   thanks    
i'm using version 2.0.22 , didn't find the bufferevent_trigger_event function  :(

**Comment by danielstock** [comment]
found it in bufferevent.h,  ver 2.1   
is there any alternate way to do it (bufferevent_trigger_event) in 2.0.22?

**Comment by azat** [comment]
>bufferevent_trigger_event) in 2.0.22?

No, but why do you stick to the 2.0.x? I would strongly suggest you to switch to 2.1.x

**Comment by danielstock** [comment]
@azat   ok, thanks for your help!!
