### ISSUE TITLE
doxygen documentation for the latest upstream

### ISSUE THREAD

**Issue by azat** [libevent/libevent#782]
Currently we only have:
- http://www.wangafu.net/~nickm/libevent-1.4/doxygen/html
- http://www.wangafu.net/~nickm/libevent-2.0/doxygen/html
- http://www.wangafu.net/~nickm/libevent-2.1/doxygen/html

@nmathewson as a hot fix (since long term solution will be to move this documentation/generation) can you add it?

**Comment by ygj6** [comment]
I found some issues related to the doxygen documentation:
- Documentation for `bufferevent_compat.h` and `rpc.h` is not generated since the `@file` command is missing. It can be fixed by adding `@file` in file comment block.
- The briefs of buffer.h,bufferevent.h and some other files are missing. Adding `@brief` command can fix it.
- The parameters in the function declaration are different from the parameters following the `@param` command.We should change them to the same.
- Documentation of `watch.h` is not generated since `watch.h` has not been added to the Doxyfile `INPUT` tag. 

The patch is here: 
   https://github.com/ygj6/libevent/commit/817d9173b294c5ffc7fdbd53d165ca173818de7e

Probably this patch help users a little bit before @nmathewson's new documentation.

**Comment by azat** [comment]
@ygj6 applied, thanks! (also I added missing link to the watch.h into event.h)

**Comment by azat** [comment]
Refs: 0546744503d36c19324d10ca772728288264441b
