### ISSUE TITLE
Proposal: Gitter room

### ISSUE THREAD

**Issue by sntdevco** [libevent/libevent#784]
I think we should just leave the GitHub issue tracker for bugs and suggestions and have a Gitter room for doubts and questions instead. That will prevent the flooding on GitHub.
Thoughts?:thought_balloon:

**Comment by azat** [comment]
Indeed, I'm thinking the same.

As for gitter, there is a [room](http://gitter.im/libevent/libevent) already (and the link to this room is in readme)

There is also irc (`#libevent on OFTC`) and [mailing list](http://archives.seul.org/libevent/users/).

Personally I do not look into irc too much (maybe few times in a month or so), but other places (mailing list, gitter and github) I monitor instantly *(but this does not means that I will respond instantly... sigh)*

*Internally we also use slack, but it is not created with publicity in mind*

**Comment by sntdevco** [comment]
So may be should put a link in the README to prevent new users from posting issues, that aren't really issues but instead are rather doubts or questions, which is not as sane to have on the issue tracker here. I'm putting a PR for adding the Gitter Room

**Comment by azat** [comment]
Good idea! Although I don't think that most reporters read the whole readme
(and there is part of your fault since it is pretty big I had some plans to
split it).

Maybe better place will be contribution guide? (CONTRIBUTING.md)

**Comment by sntdevco** [comment]
@azat How about we shift all the content to the Wiki and put a note in the README for the Wiki. And maybe also update the CONTRIBUTING.md to tell the users about asking questions on Gitter?

**Comment by sntdevco** [comment]
@azat If you give me access to the Wiki, I'll maybe organize all the content and then you can remove access? How about that?

**Comment by azat** [comment]
>How about we shift all the content to the Wiki and put a note in the README for the Wiki

I do not want to use wiki, since in this case the git repo will not have this documentation while I would prefer to keep it there, so I'm voting for creating `Documentation` (from the capital `D` to make completion easier, like in linux kernel)

>And maybe also update the CONTRIBUTING.md to tell the users about asking questions on Gitter?

Yep, that was what I suggested (and we should highlight it somehow, not with `<h1>` but somehow visible)

Actually I saw that github has some template page for issues, i.e. you can define the template of the issue per issue type (and define issue types, i.e. bug/feature/..), so I think it is better to but this into that screen.

**Comment by sntdevco** [comment]
Closing this for now, more cleanup on my TODO

**Comment by sntdevco** [comment]
@azat look at PR #786 all changes are reflected there
