### ISSUE TITLE
Question about the PR that disables EV_READ when a request is pending

### ISSUE THREAD

**Issue by wenbozhu** [libevent/libevent#794]
[PR in question](https://github.com/libevent/libevent/commit/5ff8eb26371c4dc56f384b2de35bea2d87814779#diff-f6b6aab933915430c8e4f4a5dfa99eb2L3437)

This PR broke some tests I have related to graceful server shutdown.

Questions to @theuni  etc

Is the actual issue caused by clients sending pipelined requests?

If pipleines requests are not supported, which is totally reasonable, should we just close (abort) the connection, v.s. disable EV_READ entirely?

Disabling EV_READ will make it impossible to detect "cancelled" requests, although the HTTP/1.1 spec is pretty vague in treating half-close (FIN) as cancellation. 

For my case, disabling EV-READ causes the event-loop to exit prematurely when some requests are still pending (i.e. responses are not yet ready to be written). This turns out to be a regression issue caused by this PR.

Thanks.

**Comment by azat** [comment]
Thanks for the report!

>Is the actual issue caused by clients sending pipelined requests?

AFAIR the actual issue had been caused by that fact that server request callback did not respond in place (instead if just defer the reply to another thread, see the example in the commit message)

So IOW this is not about pipelining at all, but they are indeed related to this hunk.

>For my case, disabling EV-READ causes the event-loop to exit prematurely when some requests are still pending (i.e. responses are not yet ready to be written). This turns out to be a regression issue caused by this PR.

So this said that you do deferring http replies (or I'm missing something), and you need this patch, otherwise it will/may crash. But to avoid premature conclusions, can you describe your use case?

**Comment by wenbozhu** [comment]
I was a bit lost trying to understand what "respond in place" refers to.

Isn't the case that all the servers are expected to be "event based" (no pun intended :) ... 

1) headers (and body) received) => 2) request dispatched by URls; => 3) worker thread (thread pool) handles the request (also event-driven) .... 3) ..... => 4) write the response (assuming no streaming).

The PR prevents pipelined requests from corrupting "out of place" request/response processing by disabling EV_READ, but I am suggesting we simply abort the TCP connection (if there is a safe way to do it in libevents) whenever the server sees a pipelined request. 

Thanks.

**Comment by ploxiln** [comment]
It sounds like your specific issue is that when EV_READ is no longer active for the http connection, there is no event active, and the event loop ends - but you are waiting for another thread to directly trigger the response. For some users who don't use separate threads, they may still have some other async event they are waiting for before sending the http response (perhaps another http client request or two) so the event loop will not be empty. It does seem ambiguous whether this behavior is a bug or not. If you added something like a timeout, at which point your http server stops waiting for the work thread and just responds error, that would also keep the ioloop alive.

**Comment by ploxiln** [comment]
(also, just listening for additional concurrent requests, would keep the ioloop alive ...)

**Comment by wenbozhu** [comment]
The exact issue I ran into with this PR is just a regression concern, i.e. the underlying behavior is changed which will break implementations that depend on the old behavior. 

During graceful shutdown, the listener is removed first, but otherwise the server allows all pending request/responses to run to completion.

As a work-around, I could just add a no-op event to keep the loop running. And I could live with this.

===

OTOH, I do intend to question about the actual fix which disables READ when a request is pending. 

A better fix to the root problem could be to close the connection whenever a pipelined request arrives. This will allow a server to detect a disconnected client or a cancelled request, even though it is not well defined in HTTP/1.1 specs to process half-close FIN as a cancellation. 

Thanks.

**Comment by azat** [comment]
>I was a bit lost trying to understand what "respond in place" refers to.

From 5ff8eb26371c4dc56f384b2de35bea2d87814779:

General http callback (i.e. "respond in place")

```c
static void http_cb(struct evhttp_request *req, void *arg)
{
  evhttp_send_reply(req, HTTP_OK, "Everything is fine", NULL);
}
```

And according to your comment:
> 2) request dispatched by URls; => 3) worker thread (thread pool) handles the request (also event-driven)

So IOW looks like you have something like this:

```c
static void http_cb(struct evhttp_request *req, void *arg)
{
  thread_pool_enqueue(pool, req);
}
```

So, you do not have `evhttp_send_reply*()` in this callback (like in "General callback")

But `evhttp_handle_request()` which calls your callback (`http_cb` in this case) does not ready for this (and state-machine in http.c too).

As for pipelining
> Is the actual issue caused by clients sending pipelined requests?

Indeed, but not only this, simple close can break things, since the request will be destroyed, but it will be accessed from the user callback (which is not called yet).

**Comment by wenbozhu** [comment]
Thanks for all the information and discussion. I will try to address the underlying issue in my code or come back if I run into any issues.
