### ISSUE TITLE
Why the EVBUFFER_MAX_READ is 4096？

### ISSUE THREAD

**Issue by wangpengdc** [libevent/libevent#798]
Why the EVBUFFER_MAX_READ == 4096 ？
If we set EVBUFFER_MAX_READ to a larger value and call the function(bufferevent_set_signal_max_read)，is this right？

**Comment by azat** [comment]
> Why the EVBUFFER_MAX_READ == 4096 ？

Due to historical reasons.

> If we set EVBUFFER_MAX_READ to a larger value

How? Compile libevent from sources?

> and call the function(bufferevent_set_signal_max_read)，is this right？

Kind of, but this will not set `evbuffer` internal `EVBUFFER_MAX_READ` to this value.

Anyway in 5357c3d62 new API to change `EVBUFFER_MAX_READ` had been introduced. You can compile libevent from sources (that includes the patch above, or better just pick master) and use:
- `evbuffer_set_max_read()` for `evbuffer`
- `bufferevent_set_max_single_read()` for `bufferevent`

**Comment by wangpengdc** [comment]
@azat Thanks
