### ISSUE TITLE
Multi Thread Server Issue with threads

### ISSUE THREAD

**Issue by kishans12** [libevent/libevent#826]
https://stackoverflow.com/questions/56443741/multi-threaded-c-server 

https://github.com/frknyldz/http-server-library/issues/2

Please look into this two URL shared

**Comment by azat** [comment]
This is not how you should fill the issues (and frankly - writing code).
I will take a look into this but only this time.

So AFAICS your patter is as follow:
- create one socket for listening
- share this socket for in each thread
- has your own evhttp/event_base in each thread
- allow OS to pick random thread (calling listen() from multiple threads)
- (and you do not use IOCP)

So this looks to me that OS prefer to give the request to the first thread (because all of them cannot accept() new connections right now, due to they are blocked in sleep())

You can use another threading model (that will give your more control, that I guess what you want):
- main thread: listen socket, list of workers
- worker: queue of incoming sockets
- in the main thread when you accept new connection you defer the job the worker

You can take a look at the example in [evhtp library](https://github.com/criticalstack/libevhtp/blob/00ccb5c80f7cfc3405ec39ce105f0f63a7425151/thread.c#L151) (here pipe/socketpair is used instead of queue, but AFAIK windows do not have these, although libevent has a "replacement", although not pretty good -- [evutil_socketpair](https://github.com/libevent/libevent/blob/b002f04f03ee924f7cdbe44483a74d66be2982cd/evutil.c#L202) which uses tcp socket internally)

*P.S. libevhtp is not a part of libevent*

**Comment by kishans12** [comment]
Thank You for your help @azat
