### ISSUE TITLE
Cmake builds wrong sonames

### ISSUE THREAD

**Issue by tpgxyz** [libevent/libevent#828]
When using cmake i got wrong sonames for all shared objects:

`libevent_core.so.2.1.10`

instead of right ones

`libevent_core-2.1.so.6`

**Comment by azat** [comment]
Thanks for reporting this!

This is a known issue (see the first item in #760), right now autotools should be preferred over cmake if you are cares about compatibility and so on (since they indeed differs a little bit), but we going to change this.

Are you building libevent with cmake for some distro in "production"?

**Comment by tpgxyz** [comment]
@azat I've tried to build libevent with cmake to workaround bug https://github.com/libevent/libevent/issues/827, which in case of using cmake does not occur.

Unfortunately wrong soname pushed me back to use autofoo :<

**Comment by azat** [comment]
Closing this one in favor to #760
