### ISSUE TITLE
Memory not properly released by evhttp in case of high demand of concurrent requests ?

### ISSUE THREAD

**Issue by YongtaoS** [libevent/libevent#862]
It looks like that the libevent holds the resource without proper releasing them after a high demand of concurrent download requests. For instance, in my scenario (https://github.com/libevent/libevent/issues/861), if I increase the number of concurrent requests as shown below, the memory usage increases reasonably as below.
```
#requests         memory usage (MB)
0                        2
10                      41
100                    388
200                    686
300                    1152
340                    1304
```
Once the requests are done, the memory goes back to c.a. 40MB. But if I created concurrent requests with 300 first, the memory would not go back to a reasonable level (e.g. 2 or 40 MB), c.a.  690MB instead, once the 300 requests complete. If I create 100 requests again, the memory keeps on the level of 690MB without any decrease or increase even after the complete of all requests.

So my question is how to release that memory. I appreciate much for the help.
I am using libevent-2.1.8-stable and debian 8/9.

```c
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>

#include <event2/event.h>
#include <event2/buffer.h>
#include <event2/http.h>

static const int SIZE = 4000000;

struct conn_ctx {
        struct evhttp_connection *conn;
        struct evhttp_request *req;
        int remaining;
};

void reply_chunk_cb(struct evhttp_connection *conn, void *ctx)
{
        struct conn_ctx *cctx = ctx;
        struct evbuffer *buf = evbuffer_new();
        uint8_t *dummy = (uint8_t *) malloc(SIZE);  // dynamically create the data in real cases.
        memset(dummy, 3, SIZE);
	evbuffer_add(buf, dummy, SIZE);
        evhttp_send_reply_chunk_with_cb(cctx->req, buf, reply_chunk_cb, cctx);
        evbuffer_free(buf);
        free(dummy);

	cctx->remaining--;
	if (cctx->remaining <= 0) {
                evhttp_send_reply_end(cctx->req);
                free(cctx);
                return;
        }   
}

void request_cb(struct evhttp_request *req, void *ctx)
{
	evhttp_send_reply_start(req, 200, "OK");

        struct conn_ctx *cctx = malloc(sizeof(struct conn_ctx));
        cctx->req = req;
        cctx->conn = evhttp_request_get_connection(req);
        cctx->remaining = 50;
        reply_chunk_cb(cctx->conn, cctx);
}

int
main(int argc, char **argv)
{
        struct evhttp *http;
        struct evhttp_bound_socket *handle;

        ev_uint16_t port = 480;

        if (signal(SIGPIPE, SIG_IGN) == SIG_ERR)
                return (1);

        base = event_base_new();
        if (!base) {
                return 1;
        }

        /* Create a new evhttp object to handle requests. */
        http = evhttp_new(base);
        if (!http) {
                return 1;
        }

        evhttp_set_cb(http, request_cb, NULL);

        /* Now we tell the evhttp what port to listen on */
        handle = evhttp_bind_socket_with_handle(http, "0.0.0.0", port);
        if (!handle) {
                return 1;
        }

        {
                /* Extract and display the address we're listening on. */
                struct sockaddr_storage ss;
                evutil_socket_t fd;
                ev_socklen_t socklen = sizeof(ss);
                char addrbuf[128];
                void *inaddr;
                const char *addr;
                int got_port = -1;
                fd = evhttp_bound_socket_get_fd(handle);
                memset(&ss, 0, sizeof(ss));
                if (getsockname(fd, (struct sockaddr *)&ss, &socklen)) {
                        return 1;
                }
                if (ss.ss_family == AF_INET) {
                        got_port = ntohs(((struct sockaddr_in*)&ss)->sin_port);
                        inaddr = &((struct sockaddr_in*)&ss)->sin_addr;
                } else if (ss.ss_family == AF_INET6) {
                        got_port = ntohs(((struct sockaddr_in6*)&ss)->sin6_port);
                        inaddr = &((struct sockaddr_in6*)&ss)->sin6_addr;
                } else {
                        return 1;
                }
                addr = evutil_inet_ntop(ss.ss_family, inaddr, addrbuf,
                    sizeof(addrbuf));
                if (addr) {
                        printf("Listening on %s:%d\n", addr, got_port);
                } else {
                        return 1;
                }
        }

        event_base_dispatch(base);

        return 0;
}
```

**Comment by azat** [comment]
>he memory keeps on the level of 690MB without any decrease or increase even after the complete of all requests.

How do you measure this?

Basically what `evhttp_send_reply_chunk_with_cb` does, is storing all the passed data in a buffer until it will be sent completely (it drains send already data of course).

So the possible issues can be:
- client slow read
- memory fragmentation (you can call `malloc_trim(0)` but this is not for production purpose)

**Comment by azat** [comment]
Also you may be interesting in that by default bufferevent (that internally used by http layer) will send data in 16k chunks, you can modify this using `bufferevent_set_max_single_write` and use `evhttp_set_bevcb` to create custom `bufferevent` for http connection, i.e.:

```
struct bufferevent *make_expanded_bufferevent(struct event_base *, void *arg)
{
    struct bufferevent *bev;
    bev = bufferevent_socket_new(base, -1, 0);
    if (!bev) {
        int err = bufferevent_set_max_single_write(bev, 1<<20);
        assert(!err && "bufferevent_set_max_single_write");
    }
    return bev;
}
evhttp_set_bevcb(http, make_expanded_bufferevent, NULL);
```

**Comment by YongtaoS** [comment]
Hey Azat,

Thanks a lot for the feedback! I observe those values using `top` and `htop`.

Yes, I think you are right. Your suggestions address the problem.
> client slow read

I can never reproduce the problem if I generate the requests on the local host, even the problem occurs randomly sometimes in case of using two hosts. Could you please explain why cllient slow read is related to the problem? Thank you.
> memory fragmentation

`malloc_trim(0)` does release that memory.

**Comment by azat** [comment]
> Could you please explain why cllient slow read is related to the problem?

If the client reads the data slowly, but server always adds new data, then server will need to keep in memory.

There is `bufferevent_setwatermark()`, but I guess that it will introduce more problem then it solves for the http layer. So I'm not recommending it.
But you can emulate this manually, i.e. do not send new chunks if the output buffer is greater then some threshold, i.e. something like this (**totally untested**):

```c
void reply_chunk_resched_cb(evutil_socket_t fd, short events, void *arg)
{
        struct conn_ctx *cctx = ctx;
        reply_chunk_cb(cctx->conn, ctx);
}
void reply_chunk_cb(struct evhttp_connection *conn, void *ctx)
{
        struct conn_ctx *cctx = ctx;

        struct bufferevent *bev = evhttp_connection_get_bufferevent(conn->conn);
        struct event_base *base = bufferevent_get_base(bev);
        struct evbuffer *pending = bufferevent_get_output(bev);
        /** Throttle chunks after 64K of pending data */
        if (evbuffer_get_length(pending) > 64<<10) {
            struct timeval tv;
            tv.tv_sec  = 0;
            tv.tv_usec = 100000;
            event_base_once(base, -1, EV_TIMEOUT, reply_chunk_resched_cb, ctx, &tv);
            return;
        }

        struct evbuffer *buf = evbuffer_new();
        uint8_t *dummy = (uint8_t *) malloc(SIZE);  // dynamically create the data in real cases.
        memset(dummy, 3, SIZE);
        evbuffer_add(buf, dummy, SIZE);

        evhttp_send_reply_chunk_with_cb(cctx->req, buf, reply_chunk_cb, cctx);
        evbuffer_free(buf);
        free(dummy);

        cctx->remaining--;
        if (cctx->remaining <= 0) {
                evhttp_send_reply_end(cctx->req);
                free(cctx);
                return;
        }
}
```

> malloc_trim(0) does release that memory

Actually it does not fixes the issue with slow clients, it just releases memory that was already send to client but that has not released yet, and I'm strongly suggesting you not to play with it, since this can introduce hard to debug problems and latencies.

**Comment by YongtaoS** [comment]
I can understand the server will keep more data in memory due to the flow control, if the client receives the data slowly. The question is why the memory would not be released after that. I guess it tries to hold a large continuous block of memory for send buffer fragments, in case of frequent memory fragmentation.

The emulation of rescheduling reply_chunk looks like not working. It never hits the case of >64K pending data, even >16K either.

**Comment by azat** [comment]
> The question is why the memory would not be released after that.

Memory fragmentation.

> The emulation of rescheduling reply_chunk looks like not working. It never hits the case of >64K pending data, even >16K either.

Interesting, so this means that the problem is in memory fragmentation.

But at first glance the program does not looks like the one that will
have trouble because of this, i.e. even if it is not released to the
OS it should not be a problem at all, allocator still can reuse it (you
can verify this by using malloc_stats()/mallinfo() and related)

You can implement your custom allocator (using some pool/SLAB) and tell
libevent to use them with event_set_mem_functions(), or use another
allocator (I would not suggest anything here since for the small memory
footprint I think they will have more memory reserved then glibc).

**Comment by YongtaoS** [comment]
The program does reuse that memory. That is the reason for
> If I create 100 requests again, the memory keeps on the level of 690MB without any decrease or increase even after the complete of all requests,

The problem now I am facing is that if that memory is not released to the OS, other programs cannot get more memory from the OS, even there are enough memory.

**Comment by azat** [comment]
On Fri, Aug 2, 2019 at 5:06 PM ys <notifications@github.com> wrote:
>
> The program does reuse that memory. That is the reason for
>
> If I create 100 requests again, the memory keeps on the level of 690MB without any decrease or increase even after the complete of all requests,
>
> The problem now I am facing is that if that memory is not released to the OS, other programs cannot get more memory from the OS, even there are enough memory.

Well you can tune overcommit (on linux /proc/sys/vm/overcommit_memory)
and/or enable swap, but this can (and I guess *will*) slow down the
whole system.

I would prefer to add more memory there (i.e. double), but yes, this
is not always possible or/and great solution.

So I guess that the only option you have - is replace malloc (and
friends) for libevent and release memory as soon as possible, it
should not be that hard if the object size is static, and memory that
allocated for evbuffer chains is aligned, but you could face with
other problems like vm mappings manipulation overhead (munmap()) and
so on, that's why it is hard to release memory as-soon-as-possible and
that's why modern allocators do not do this, it is simply profitable
(plus nowadays memory is not that costly).

**Comment by YongtaoS** [comment]
Unfortunately, static object size is not my real case. The size varies dynamically.
Anyways, thanks a lot!

**Comment by ploxiln** [comment]
for some workloads, [jemalloc](https://github.com/jemalloc/jemalloc) is better about avoiding fragmentation and releasing memory back to the system, than the glibc built-in allocator

**Comment by YongtaoS** [comment]
Hey ploxilin, jemalloc sounds like a good option! Thank you!

I am also wondering whether it could be another solution if I allocate the memory always with a constant size and feed them to send_reply_chunk() with a specific constant size. It looks like the problem is reproducible if using dynamic varying sizes, but occurs rarely if the size is fixed. My knowledge about OS is very limited.

**Comment by ploxiln** [comment]
Yeah, maybe ... how this works is that the allocator library (typically provided by libc if you don't override it with one like jemalloc) gets big chunks of memory from the OS, and then gives out small chunks when you call `malloc()`, and puts those small chunks back in the "free pool" when you call `free()`. If any part of the big chunk from the OS is still in use, none of it can be released back to the OS. Always allocating the same size can help, because then anything you `free()` can be more easily reused, and that may make it less likely that the next allocation comes from a newer "big chunk", so that newer "big chunk" is more likely to be released to the OS. But it really depends on the allocation patterns, including the allocations and frees of other libraries you use. What happens sometimes is that you allocate and use a bunch of memory, and then some small unrelated function allocates a little bit of long-lived information, and it ends up in a large chunk along with your bunch of application data. Then you free all that application data, and the big chunk is 99% free, but it can't be released to the OS because of that little unrelated bit. It's not easy to avoid this problem.

**Comment by YongtaoS** [comment]
Great, appreciate much for the explanation of you guys.
will try and close the issue later if no more problems pop up.

**Comment by azat** [comment]
> will try and close the issue later if no more problems pop up.

@YongtaoS any update?

**Comment by YongtaoS** [comment]
no, i was quite busy at the moment, but will be back to the topic after that and update the results here. So i close the issue first.
