### ISSUE TITLE
Uninstall.cmake.in is missing from 2.1.11 release

### ISSUE THREAD

**Issue by theirix** [libevent/libevent#863]
Trying to build a fresh 2.1.11 release. It introduces generating `Uninstall.cmake` but the source file `cmake/Uninstall.cmake.in` is missing from the official archive so build fails. Release notes said to use libevent-2.1.11-stable.tar.gz (not the sources generated by github automatically).

Reproducing (on macOS):
```
cmake -DEVENT__DISABLE_OPENSSL=True .
...
CMake Error: File /Users/irix/Downloads/libevent-2.1.11-stable/cmake/Uninstall.cmake.in does not exist.
CMake Error at CMakeLists.txt:1498 (configure_file):
  configure_file Problem configuring file
```

**Comment by azat** [comment]
Thanks for the report!

Fixed in upstream, but it will not be fixed in dist archive, since it had been released already

> Release notes said to use libevent-2.1.11-stable.tar.gz (not the sources generated by github automatically).

Well let's me elaborate this a little, libevent's cmake support is in beta stage for now, so it is recommended to use autotools build, and this dist archive is only related to autotools, IOW it is perfectly fine to use sources generated by github if you are using cmake.

**Comment by theirix** [comment]
Thanks for the quick fix!

Sure, I was aware of experimental support for CMake for previous versions of libevent but I thought CMake became an official build method since 2.1.10 when it was reflected in documentation (Building.md).
