### ISSUE TITLE
Persistent Timer w/ Immediate Activation

### ISSUE THREAD

**Issue by damonearp** [libevent/libevent#872]
I'm looking to run some code every N seconds, including immediately after dispatching the event base. Naturally `event_active` to the rescue! And indeed the callback is immediately called, however the second invocation of the callback is delayed for 2 times the timeout.

##### Test Case -- Debian 9.9 -- v2.0.21

```c
#include <event2/event.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

static struct timeval LAST;

static void refresh(int fd, short flags, void *userdata)
{   
    struct timeval now, diff;
    gettimeofday(&now, NULL);
    timersub(&now, &LAST, &diff);
    printf("%ld.%06ld\n", diff.tv_sec, diff.tv_usec);
    LAST = now;
}

int main(int argc, const char *argv[])
{
    struct event_base *base = event_base_new();
    struct event *event = event_new(base, -1, EV_PERSIST, refresh, NULL);
    struct timeval timeout = { .tv_sec = 1, .tv_usec = 0 };
    event_add(event, &timeout);
    event_active(event, EV_TIMEOUT, 0);
    gettimeofday(&LAST, NULL);
    event_base_dispatch(base);
    return 0;
}
```

##### Output
```sh
$ gcc -Wall -Werror -o timer -levent timer.c  && ./timer 
0.000005
2.002123
0.999116
1.000130
1.000115
^C
```

As you can see by using `event_active` I guarantee the second invocation of refresh will be `2 * timeout`. When I set `timeout.tv_sec` to 5 the second call to `refresh()` is 10 seconds after the first call instead of 5. This only affects timers setup with `EV_PERSIST`. If `event_active` is called on the `struct event*` M times, then the invocation after the last one will be `(M + 1) * timeout`. 

To work around this I'm using one-shot timers: first `event_add` uses a 0 sec timeout then all others the N second timeout. I can then use `event_active` as much as I like and libevent will trigger the event again N seconds after the last one.

**Comment by azat** [comment]
Yep, looks like a bug, I will take a look, many thanks for the reproducer!

**Comment by azat** [comment]
A little introduction on how timeouts works, once you schedule adds the event with the timeout the event's deadline is calculated, this is when the event should be called if it did not triggered before. And if the event timedout, and this is persistent event (`EV_PERSIST`), then another **timeout interval added to the current event's deadline** (now current time).

So, once event with `EV_TIMEOUT|EV_PERSIST` activated it adds another timeout to the timeout deadline, and it does not distinguish `event_active()` from regular timeouts anyhow, so hence the deadline will be `now + 2 seconds` (in your case).

You can avoid this by not passing `EV_TIMEOUT` to the `event_active()`, since in this case the event will be triggered as regular, and the event's timeout will be recalculated from now instead of from the previous timeout deadline.

P.S. let's keep this open for awhile, maybe we should change default behavior of event_active() in this case

**Comment by damonearp** [comment]
Didn't occur to me to just pass a `0`, oh well. Thanks for the analysis, and I'll leave it to youall to determine the best course forward. Thanks for this great tool!

**Comment by azat** [comment]
>maybe we should change default behavior of event_active() in this case

Let's keep it as-is, to avoid behavior changes.
