### ISSUE TITLE
Window10 x86 issue vs 2015, bufferevent_write() in other thead，client recv nothing

### ISSUE THREAD

**Issue by leanme** [libevent/libevent#912]
Pseudocode：
Version: libevent-2.1.11-stable
```
void  worker_thread(void* arg){
        auto context = (struct requestcontext*)arg;
        auto bev = arg->bev;

        bufferevent_lock(bev);
        bufferevent_write(bev,"123",3);  
        bufferevent_unlock(bev);
        printf("worker_thread\n");
}

void write_cb(bev) {
      printf("read_cb\n");
}

void read_cb(bev) {
           bufferevent_lock(bev);
           bufferevent_read(bev,&body);
           bufferevent_unlock(bev);

           printf("read_cb\n");
          
           // bufferevent_write(bev,"321",3);  // case 2: uncomment this line.
           send_to_worker_thread(body); // emit data to thread
}

void main(){
      start_work_thread();
      listen_and_serve(...);
}
```
#### case 1:
send any data to server,but nothing return with `write_cb` printed.

#### case 2:
send any data to server,recv `123` and `321` both!

Any problem with my implement,thank you!

**Comment by azat** [comment]
>        bufferevent_lock(bev);
>        bufferevent_write(bev,"123",3);  
>        bufferevent_unlock(bev);

You don't need to manually lock the bev, it will be done automatically, but only if the locking is enabled, for this you need to call `evthread_use_windows_threads()` (once at the beginning, before using any libevent API) and use `BEV_OPT_THREADSAFE`

*(same for the read)*

>case 1:
>send any data to server,but nothing return with write_cb printed.
>
>case 2:
>send any data to server,recv 123 and 321 both!
>
>Any problem with my implement,thank you!

Sorry, but I did not understand this, can you share 100-200 lines of working code so I can take a look?

But at least this code looks suspicious:

```
      start_work_thread();
      listen_and_serve(...);
```

since according to your pseudo-code this will call `bufferevent_write()` before server started

**Comment by leanme** [comment]
`evthread_use_windows_threads` can solve my problem,thank you @azat 
This is my first time to use libevent as net layer of  my rpc framework,thank you again.

**Comment by azat** [comment]
>This is my first time to use libevent as net layer of my rpc framework,

In this case I would recommend you to avoid multi threading for now and add it only if it is required
