### ISSUE TITLE
It is ok to call libevent functions again after libevent_global_shutdown?

### ISSUE THREAD

**Issue by Barricade** [libevent/libevent#922]
It is ok to call libevent functions again after libevent_global_shutdown?

**Comment by azat** [comment]
Yes, since `libevent_global_shutdown` should initialize some globals to default state, hence they will be initialized again once you call appropriate functions (and don't forget to call initialize functions again if you need the functionality that they enable, i.e. `evthread_use_pthreads` for threading support)
