### ISSUE TITLE
CentOS 6.10 yum no package libevent-devel available

### ISSUE THREAD

**Issue by Ezyweb-uk** [libevent/libevent#925]
Trying to update Cpanel from v11.82 to v11.84 and it fails with the message: `libevent is needed by cpanel-perl-528-DNS-Unbound-0.09-3.cp1180.x86_64`

Tried: 
`yum install -y libevent libevent-devel` 
but got the messages:
`No package libevent available.
No package libevent-devel available` 

Any solutions please?

**Comment by azat** [comment]
According to the [pkgs.org](https://pkgs.org/download/libevent-devel) it is available.

Can't verify this using this `centos:centos6.10` docker image, since it is too old:

```
[1874180.728213] bash[3077665] vsyscall attempted with vsyscall=none ip:ffffffffff600400 cs:33 sp:7fffffffec48 ax:ffffffffff600400 si:7fffffffef61 di:0
[1874180.728216] bash[3077665]: segfault at ffffffffff600400 ip ffffffffff600400 sp 00007fffffffec48 error 15
```

Okay, found kernel without `CONFIG_LEGACY_VSYSCALL_NONE=y`:

```
$ docker run --rm -it centos:centos6.10
# yum install -y libevent libevent-devel
...
Installed:
  libevent.x86_64 0:1.4.13-4.el6                                                         libevent-devel.x86_64 0:1.4.13-4.el6

Dependency Installed:
  libevent-doc.noarch 0:1.4.13-4.el6                                                      libevent-headers.noarch 0:1.4.13-4.el6

Complete!
```

That said that something wrong with your env, maybe you do not have some standard repos?

**Comment by Ezyweb-uk** [comment]
CentOS and epel repos were found to be disabled.
@azat thanks for your help!
