### ISSUE TITLE
evbuffer customization

### ISSUE THREAD

**Issue by ymantijunk** [libevent/libevent#935]
I'd like to change following in evbuffer, any suggestions?

1. maintain all the chains of the same size, say 32K each. 
2. the chain to be full before filling data to the next chain. Currently, if the first chain has N bytes free and the new space is request for > N bytes, it seems to be allocating new chain rather than using N bytes from the previous chain. 

Also, what are the function needs to be replaced if we need to have our own buffer implementation

Thank you for your inputs

**Comment by azat** [comment]
Hi!

>maintain all the chains of the same size, say 32K each.

The easiest way will be to wrap `evbuffer_*` functions to limit the data to 32k, and use [`evbuffer_set_max_read()`](http://libevent.org/doc/buffer_8h.html#ac5441fc0ce576ad997bf1a869f8c4ba9) in addition to number of bytes read from fd. 

Althoug you can modify [`evbuffer_chain_new()`](https://github.com/libevent/libevent/blob/ea12428db66a2c82b57c12afaf5fb5d1a0935f3c/buffer.c#L159), and it's callers, since the callers assume that the chain will contain at least requested bytes, and if you split chains by 32k then this will  not always true, but this is complex and I don't see any benefits in this way

Also just out of curiosity, why do you need this? Maybe it is easier to change the allocator? (evbuffer already rounds the allocation to the power of two, so this should not be a great problem for the allocators in general, but I think I can find some ways to expose memory fragmentation issues with this).

*But if you will describe your case and it will be more or less general this can be implemented as additional API to the evbuffer*

> the chain to be full before filling data to the next chain. Currently, if the first chain has N bytes free and the new space is request for > N bytes, it seems to be allocating new chain rather than using N bytes from the previous chain.

This can implemented as a flag for the evbuffer (see `evbuffer_set_flags()`).

> Also, what are the function needs to be replaced if we need to have our own buffer implementation

I guess, most of them :) (but I'm not sure what exactly "own buffer implementation" means, sometimes it can be possible to simply add wrappers, sometimes not)

**Comment by azat** [comment]
If you have any other questions, please reopen or create new issue
