### ISSUE TITLE
How to flush writes during an long callback?

### ISSUE THREAD

**Issue by thefallentree** [libevent/libevent#936]
So I have an situation where in an event callback where I execute an function synchronously,  during the execution some output will be generated (the output will be written to 1 or more buffevent), and I want it flush it out to the users. what's the best way to do it?  I want this to be writing only, don't actually want to accept user input at the time or handling socket closure even.

**Comment by azat** [comment]
bufferevent writes the data via the event loop (it waits `EV_WRITE` and only after this it can write to fd), so first of all you need to make sure that the callback is not executed from the same thread as the thread that executes event loop for that bufferevent, if this is true than this should work (otherwise it is not possible, by obvious reasons)

> want this to be writing only, don't actually want to accept user input at the time or handling socket closure even.

You just need to disable EV_READ, i.e. `bufferevent_disable(bev,EV_READ)`

**Comment by thefallentree** [comment]
Well, The whole program is an single thread, so it  didn’t matter which
thread I am on, I am always on the wrong thread it seems :-D

I think what I need is an way to flush an bufferevent ,  that is, try to
write to underlaying socket once, if it is writable then write as much as
possible, if not then just ignore it.

**Comment by azat** [comment]
Actually this can be done even with one thread, but you need to yield your calback, i.e. calling periodically `event_base_loop(base, EVLOOP_NONBLOCK)` within your callback, but this will process not only write but other events too (timers, signals, ...)

**Comment by thefallentree** [comment]
Yeah that won’t work for me. Because I need to only process writes.  BTW
Why does socket based bufferevent flush does nothing?

Another option I can think of is that I can run bufferevents ‘s base in an
dedicated network thread and schedule callbacks on to main event loop .
That way network thread is always running , meaning whatever we write has
an chance of going out soonish.

**Comment by azat** [comment]
> Yeah that won’t work for me. Because I need to only process writes. BTW
> Why does socket based bufferevent flush does nothing?

It writes only when EV_WRITE is possible, to avoid blocking, hence it
does nothing.

> Another option I can think of is that I can run bufferevents ‘s base in an
> dedicated network thread and schedule callbacks on to main event loop .
> That way network thread is always running , meaning whatever we write has
> an chance of going out soonish.

Indeed, and I think that this is correct way to go (of course if you
do not want to yield from your callback periodically, you can use
"event_base_once(base, -1, 0, callback, some_context, timeout)" to
trigger it again after some timeout)

> > calling periodically event_base_loop(base, EVLOOP_NONBLOCK)
> > within your callback

Ignore this suggestion, this will not work, since you cannot call
event_base_loop() inside loop.

**Comment by azat** [comment]
Do you have any other questions? If no, can you please close the issue? Thanks

**Comment by thefallentree** [comment]
thank you! I will try to adopt the dedicated network thread way.

**Comment by thefallentree** [comment]
@azat  is it possible to change bufferevent_flush behavior on socket based buffervent to write at least once, and if write returns EWOULDBLOCK it simply doesn't do anything?

**Comment by azat** [comment]
Yes, I guess should not break any existing code, would you mind to contribute this functionality?

It should have:
- flush for sock
- flush for openssl
- flush for async
- unit tests

**Comment by IronsDu** [comment]
Hi, does the latest version still not support flush the buffer to socket immediately?

**Comment by thefallentree** [comment]
it still doesn’t, but I have some code that appears to work fine, can post it later.
