### ISSUE TITLE
Why evhttp_connection_get_peer return peer_addr is null in gencb_http_handler callback?

### ISSUE THREAD

**Issue by okayabc** [libevent/libevent#988]

**Comment by azat** [comment]
First of all, what is `gencb_http_handler`? I guess this is the callback that you passed to `evhttp_set_gencb`.

`evhttp_connection_get_peer` works only for outgoing connections (since as [doc](http://libevent.org/doc/http_8h.html#a2e1ef33f629aa655bb58ae2cee977d93) says, it just simply returns the associated with the connection address, but yes, it is unclear and can be fixed), you can use `evhttp_connection_get_addr` instead

P.S. Please be a little more verbose and accurate when you submitting issues, you can also take a look at some [guides](https://medium.com/nyc-planning-digital/writing-a-proper-github-issue-97427d62a20f)
